module.exports = {
	imgUrl: "https://rawcdn.githack.com/SM64-TAS-ABC/STROOP/c260e427ad9e4533b4eb00845059478cd7307b57/STROOP/Resources/Object Images/",
	courses: [
		/* 0 */ "Bob-omb Battlefield",
		/* 1 */ "Whomp's Fortress",
		/* 2 */ "Jolly Roger Bay",
		/* 3 */ "Cool, Cool Mountain",
		/* 4 */ "Big Boo's Haunt",
		/* 5 */ "Hazy Maze Cave",
		/* 6 */ "Lethal Lava Land",
		/* 7 */ "Shifting Sand Land",
		/* 8 */ "Dire, Dire Docks",
		/* 9 */ "Snowman's Land",
		/* 10 */ "Wet-Dry World",
		/* 11 */ "Tall, Tall Mountain",
		/* 12 */ "Tiny-Huge Island",
		/* 13 */ "Tick-Tock Clock",
		/* 14 */ "Rainbow Ride",
		/* 15 */ "Bowser in the Dark World",
		/* 16 */ "Bowser in the Fire Sea",
		/* 17 */ "Bowser in the Sky",
		/* 18 */ "The Princess's Secret Slide",
		/* 19 */ "Cavern of the Metal Cap",
		/* 20 */ "Tower of the Wing Cap",
		/* 21 */ "Vanish Cap under the Moat",
		/* 22 */ "Wing Mario Over the Rainbow",
		/* 23 */ "The Secret Aquarium",
		/* 24 */ "Inside Castle",
		/* 25 */ "Castle Grounds"
	], stars: [
		/* 0 */ { course: 0, id: 1, name: "Big Bob-omb on the Summit" },
		/* 1 */ { course: 0, id: 2, name: "Footrace with Koopa the Quick" },
		/* 2 */ { course: 0, id: 3, name: "Shoot to the Island in the Sky" },
		/* 3 */ { course: 0, id: 4, name: "Find the 8 Red Coins" },
		/* 4 */ { course: 0, id: 5, name: "Mario Wings to the Sky" },
		/* 5 */ { course: 0, id: 6, name: "Behind Chain Chomp's Gate" },

		/* 6 */ { course: 1, id: 1, name: "Chip Off Whomp's Block" },
		/* 7 */ { course: 1, id: 2, name: "To the Top of the Fortress" },
		/* 8 */ { course: 1, id: 3, name: "Shoot into the Wild Blue" },
		/* 9 */ { course: 1, id: 4, name: "Red Coins on the Floating Isle" },
		/* 10 */ { course: 1, id: 5, name: "Fall onto the Caged Island" },
		/* 11 */ { course: 1, id: 6, name: "Blast Away the Wall" },

		/* 12 */ { course: 2, id: 1, name: "Plunder in the Sunken Ship" },
		/* 13 */ { course: 2, id: 2, name: "Can the Eel Come Out to Play?" },
		/* 14 */ { course: 2, id: 3, name: "Treasure of the Ocean Cave" },
		/* 15 */ { course: 2, id: 4, name: "Red Coins on the Ship Afloat" },
		/* 16 */ { course: 2, id: 5, name: "Blast to the Stone Pillar" },
		/* 17 */ { course: 2, id: 6, name: "Through the Jet Stream" },

		/* 18 */ { course: 3, id: 1, name: "Slip Slidin' Away" },
		/* 19 */ { course: 3, id: 2, name: "Li'l Penguin Lost" },
		/* 20 */ { course: 3, id: 3, name: "Big Penguin Race" },
		/* 21 */ { course: 3, id: 4, name: "Frosty Slide for 8 Red Coins" },
		/* 22 */ { course: 3, id: 5, name: "Snowman's Lost His Head" },
		/* 23 */ { course: 3, id: 6, name: "Wall Kicks Will Work" },

		/* 24 */ { course: 4, id: 1, name: "Go on a Ghost Hunt" },
		/* 25 */ { course: 4, id: 2, name: "Ride Big Boo's Merry-Go-Round" },
		/* 26 */ { course: 4, id: 3, name: "Secret of the Haunted Books" },
		/* 27 */ { course: 4, id: 4, name: "Seek the 8 Red Coins" },
		/* 28 */ { course: 4, id: 5, name: "Big Boo's Balcony" },
		/* 29 */ { course: 4, id: 6, name: "Eye to Eye in the Secret" },

		/* 30 */ { course: 5, id: 1, name: "Swimming Beast in the Cavern" },
		/* 31 */ { course: 5, id: 2, name: "Elevate for 8 Red Coins" },
		/* 32 */ { course: 5, id: 3, name: "Metal-Head Mario Can Move!" },
		/* 33 */ { course: 5, id: 4, name: "Navigating the Toxic Maze" },
		/* 34 */ { course: 5, id: 5, name: "A-Maze-Ing Emergency Exit" },
		/* 35 */ { course: 5, id: 6, name: "Watch for Rolling Rocks" },

		/* 36 */ { course: 6, id: 1, name: "Boil the Big Bully" },
		/* 37 */ { course: 6, id: 2, name: "Bully the Bullies" },
		/* 38 */ { course: 6, id: 3, name: "8-Coin Puzzle with 15 Pieces" },
		/* 39 */ { course: 6, id: 4, name: "Red-Hot Log Rolling" },
		/* 40 */ { course: 6, id: 5, name: "Hot-Foot-It into the Volcano" },
		/* 41 */ { course: 6, id: 6, name: "Elevator Tour in the Volcano" },

		/* 42 */ { course: 7, id: 1, name: "In the Talons of the Big Bird" },
		/* 43 */ { course: 7, id: 2, name: "Shining Atop the Pyramid" },
		/* 44 */ { course: 7, id: 3, name: "Inside the Ancient Pyramid" },
		/* 45 */ { course: 7, id: 4, name: "Stand Tall on the Four Pillars" },
		/* 46 */ { course: 7, id: 5, name: "Free Flying for 8 Red Coins" },
		/* 47 */ { course: 7, id: 6, name: "Pyramid Puzzle" },

		/* 48 */ { course: 8, id: 1, name: "Board Bowser's Sub" },
		/* 49 */ { course: 8, id: 2, name: "Chests in the Current" },
		/* 50 */ { course: 8, id: 3, name: "Pole-Jumping for Red Coins" },
		/* 51 */ { course: 8, id: 4, name: "Through the Jet Stream" },
		/* 52 */ { course: 8, id: 5, name: "The Manta Ray's Reward" },
		/* 53 */ { course: 8, id: 6, name: "Collect the Caps..." },

		/* 54 */ { course: 9, id: 1, name: "Snowman's Big Head" },
		/* 55 */ { course: 9, id: 2, name: "Chill with the Bully" },
		/* 56 */ { course: 9, id: 3, name: "In the Deep Freeze" },
		/* 57 */ { course: 9, id: 4, name: "Whirl from the Freezing Pond" },
		/* 58 */ { course: 9, id: 5, name: "Shell Shreddin' for Red Coins" },
		/* 59 */ { course: 9, id: 6, name: "Into the Igloo" },

		/* 60 */ { course: 10, id: 1, name: "Shocking Arrow Lifts!" },
		/* 61 */ { course: 10, id: 2, name: "Top o' the Town" },
		/* 62 */ { course: 10, id: 3, name: "Secrets in the Shallows & Sky" },
		/* 63 */ { course: 10, id: 4, name: "Express Elevator--Hurry Up!" },
		/* 64 */ { course: 10, id: 5, name: "Go to Town for Red Coins" },
		/* 65 */ { course: 10, id: 6, name: "Quick Race Through Downtown!" },

		/* 66 */ { course: 11, id: 1, name: "Scale the Mountain" },
		/* 67 */ { course: 11, id: 2, name: "Mystery of the Monkey Cage" },
		/* 68 */ { course: 11, id: 3, name: "Scary 'Shrooms, Red Coins" },
		/* 69 */ { course: 11, id: 4, name: "Mysterious Mountainside" },
		/* 70 */ { course: 11, id: 5, name: "Breathtaking View from Bridge" },
		/* 71 */ { course: 11, id: 6, name: "Blast to the Lonely Mushroom" },

		/* 72 */ { course: 12, id: 1, name: "Pluck the Piranha Flower" },
		/* 73 */ { course: 12, id: 2, name: "The Tip Top of the Huge Island" },
		/* 74 */ { course: 12, id: 3, name: "Rematch with Koopa the Quick" },
		/* 75 */ { course: 12, id: 4, name: "Five Itty Bitty Secrets" },
		/* 76 */ { course: 12, id: 5, name: "Wiggler's Red Coins" },
		/* 77 */ { course: 12, id: 6, name: "Make Wiggler Squirm" },

		/* 78 */ { course: 13, id: 1, name: "Roll into the Cage" },
		/* 79 */ { course: 13, id: 2, name: "The Pit and the Pendulums" },
		/* 80 */ { course: 13, id: 3, name: "Get a Hand" },
		/* 81 */ { course: 13, id: 4, name: "Stomp on the Thwomp" },
		/* 82 */ { course: 13, id: 5, name: "Timed Jumps on Moving Bars" },
		/* 83 */ { course: 13, id: 6, name: "Stop Time for Red Coins" },

		/* 84 */ { course: 14, id: 1, name: "Cruiser Crossing the Rainbow" },
		/* 85 */ { course: 14, id: 2, name: "The Big House in the Sky" },
		/* 86 */ { course: 14, id: 3, name: "Coins Amassed in a Maze" },
		/* 87 */ { course: 14, id: 4, name: "Swingin' in the Breeze" },
		/* 88 */ { course: 14, id: 5, name: "Tricky Triangles!" },
		/* 89 */ { course: 14, id: 6, name: "Somewhere Over the Rainbow" },

		/* 90 */ { course: 18, id: 1, name: "One of the Castle's Secret Stars!" },
		/* 91 */ { course: 18, id: 2, name: "One of the Castle's Secret Stars!" },
		/* 92 */ { course: 23, id: 1, name: "One of the Castle's Secret Stars!" },
		/* 93 */ { course: 15, id: 1, name: "One of the Castle's Secret Stars!" },
		/* 94 */ { course: 24, id: 1, name: "One of the Castle's Secret Stars!" },
		/* 95 */ { course: 24, id: 2, name: "One of the Castle's Secret Stars!" },
		/* 96 */ { course: 24, id: 3, name: "One of the Castle's Secret Stars!" },
		/* 97 */ { course: 20, id: 1, name: "One of the Castle's Secret Stars!" },
		/* 98 */ { course: 19, id: 1, name: "One of the Castle's Secret Stars!" },
		/* 99 */ { course: 21, id: 1, name: "One of the Castle's Secret Stars!" },
		/* 100 */ { course: 24, id: 4, name: "One of the Castle's Secret Stars!" },
		/* 101 */ { course: 24, id: 5, name: "One of the Castle's Secret Stars!" },
		/* 102 */ { course: 16, id: 1, name: "One of the Castle's Secret Stars!" },
		/* 103 */ { course: 22, id: 1, name: "One of the Castle's Secret Stars!" },
		/* 104 */ { course: 17, id: 1, name: "One of the Castle's Secret Stars!" }
	], dialogs: [
		/* 0 */ { course: 0, actor: "Level Entrance", icon: "Mario", split: 4, text: "Wow! You're smack in the\nmiddle of the battlefield.\nYou'll find the Power\nStars that Bowser stole\ninside the painting\nworlds.\nFirst, talk to the\nBob-omb Buddy. (Press [B]\nto talk.) He'll certainly\nhelp you out, and so will\nhis comrades in other\nareas.\nTo read signs, stop, face\nthem and press [B]. Press [A]\nor [B] to scroll ahead. You\ncan talk to some other\ncharacters by facing them\nand pressing [B]." },
		/* 1 */ { course: 0, icon: "Bob-omb Buddy", split: 4, text: "Watch out! If you wander\naround here, you're liable\nto be plastered by a\nwater bomb!\nThose enemy Bob-ombs love\nto fight, and they're\nalways finding ways to\nattack.\nThis meadow has become\na battlefield ever since\nthe Big Bob-omb got his\npaws on the Power Star.\nCan you recover the Star\nfor us? Cross the bridge\nand go left up the path\nto find the Big Bob-omb.\nPlease come back to see\nme after you've retrieved\nthe Power Star!" },
		/* 2 */ { course: 0, icon: "Bob-omb Buddy", split: 4, text: "Hey, you! It's dangerous\nahead, so listen up! Take\nmy advice.\n\nCross the two\nbridges ahead, then\nwatch for falling\nwater bombs.\nThe Big Bob-omb at the\ntop of the mountain is\nvery powerful--don't let\nhim grab you!\nWe're Bob-omb Buddies,\nand we're on your side.\nYou can talk to us\nwhenever you'd like to!" },
		/* 3 */ { course: 0, icon: "Bob-omb Buddy", split: 5, text: "Thank you, Mario! The Big\nBob-omb is nothing but a\nbig dud now! But the\nbattle for the castle has\njust begun.\nOther enemies are holding\nthe other Power Stars. If\nyou recover more Stars,\nyou can open new doors\nthat lead to new worlds!\nMy Bob-omb Buddies are\nwaiting for you. Be sure\nto talk to them--they'll\nset up cannons for you." },
		/* 4 */ { course: 0, icon: "Bob-omb Buddy", split: 3, text: "We're peace-loving\nBob-ombs, so we don't use\ncannons.\nBut if you'd like\nto blast off, we don't\nmind. Help yourself.\nWe'll prepare all of the\ncannons in this course for\nyou to use. Bon Voyage!" },
		/* 5 */ { course: 0, icon: "Koopa the Quick", split: 3, text: "Hey, Mario! Is it true\nthat you beat the Big\nBob-omb? Cool!\nYou must be strong. And\npretty fast. So, how fast\nare you, anyway?\nFast enough to beat me...\nKoopa the Quick? I don't\nthink so. Just try me.\nHow about a race to the\nmountaintop, where the\nBig Bob-omb was?\nWhaddya say? When I say\n\"Go,\" let the race begin!\n\nReady....\n\n//Go!////Don't Go" },
		/* 6 */ { course: 0, actor: "Koopa the Quick", icon: "Koopa the Quick with Flag", split: 3, text: "Hey!!! Don't try to scam\nME. You've gotta run\nthe whole course.\nLater. Look me up when\nyou want to race for\nreal." },
		/* 7 */ { course: 0, actor: "Koopa the Quick", icon: "Koopa the Quick with Flag", split: 5, text: "Hufff...\u200bfff...\u200bpufff...\nWhoa! You...\u200breally...\u200bare...\nfast! A human blur!\nHere you go--\u200byou've won\nit, fair and square!" },
		/* 8 */ { course: 0, icon: "Sign", split: 4, text: "BEWARE OF CHAIN CHOMP\nExtreme Danger!\nGet close and press [C]↑\nfor a better look.\nScary, huh?\nSee the Red Coin on top\nof the stake?\n\nWhen you collect eight of\nthem, a Power Star will\nappear in the meadow\nacross the bridge." },
		/* 9 */ { course: 12, icon: "Koopa the Quick", split: 4, text: "Long time, no see! Wow,\nhave you gotten fast!\nHave you been training\non the sly, or is it the\npower of the Stars?\nI've been feeling down\nabout losing the last\nrace. This is my home\ncourse--how about a\nrematch?\nThe goal is in\nWindswept Valley.\nReady?\n\n//Go//// Don't Go" },
		/* 10 */ { course: 20, icon: "Wing Cap Switch Button", split: 4, text: "You've stepped on the\nWing Cap Switch. Wearing\nthe Wing Cap, you can\nsoar through the sky.\nNow Wing Caps will pop\nout of all the red blocks\nyou find.\n\nWould you like to Save?\n\n//Yes////No" },
		/* 11 */ { course: 19, icon: "Metal Cap Switch Button", split: 4, text: "You've just stepped on\nthe Metal Cap Switch!\nThe Metal Cap makes\nMario invincible.\nNow Metal Caps will\npop out of all of the\ngreen blocks you find.\n\nWould you like to Save?\n\n//Yes////No" },
		/* 12 */ { course: 21, icon: "Vanish Cap Switch Button", split: 4, text: "You've just stepped on\nthe Vanish Cap Switch.\nThe Vanish Cap makes\nMario disappear.\nNow Vanish Caps will pop\nfrom all of the blue\nblocks you find.\n\nWould you like to Save?\n\n//Yes////No" },
		/* 13 */ { actor: "Level Exit", icon: "Power Star Yellow", split: 5, text: "You've collected 100\ncoins! Mario gains more\npower from the castle.\nDo you want to Save?\n//Yes////No" },
		/* 14 */ { actor: "Level Exit", icon: "Power Star Yellow", split: 4, text: "Wow! Another Power Star!\nMario gains more courage\nfrom the power of the\ncastle.\nDo you want to Save?\n\n//You Bet//Not Now" },
		/* 15 */ { course: 0, icon: "Sign", split: 4, text: "You can punch enemies to\nknock them down. Press [A]\nto jump, [B] to punch.\nPress [A] then [B] to Kick.\nTo pick something up,\npress [B], too. To throw\nsomething you're holding,\npress [B] again." },
		/* 16 */ { course: [7, 6, 9], icon: "Sign", split: 3, text: "Hop on the shiny shell and\nride wherever you want to\ngo! Shred those enemies!" },
		/* 17 */ { course: 0, icon: "King Bob-omb", split: 4, text: "I'm the Big Bob-omb, lord\nof all blasting matter,\nking of ka-booms the\nworld over!\nHow dare you scale my\nmountain? By what right\ndo you set foot on my\nimperial mountaintop?\nYou may have eluded my\nguards, but you'll never\nescape my grasp...\n\n...and you'll never take\naway my Power Star. I\nhereby challenge you,\nMario!\nIf you want the Star I\nhold, you must prove\nyourself in battle.\n\nCan you pick me up from\nthe back and hurl me to\nthis royal turf? I think\nthat you cannot!" },
		/* 18 */ { course: 1, icon: "Sign", split: 4, text: "I'm sleeping because...\n...I'm sleepy. I don't\nlike being disturbed.\nPlease walk quietly." },
		/* 19 */ { course: 24, icon: "Bulletin Board", split: 2, text: "Shhh! Please walk\nquietly in the hallway!" },
		/* 20 */ { course: 25, icon: "Peach", split: 6, text: "Dear Mario:\nPlease come to the\ncastle. I've baked\na cake for you.\nYours truly--\nPrincess Toadstool" },
		/* 21 */ { course: 24, actor: "Bowser", icon: "Bowser Breathing", split: 5, text: "Welcome.\nNo one's home!\nNow scram--\nand don't come back!\nGwa ha ha!" },
		/* 22 */ { course: 24, actor: "Door", icon: "Door Key", split: 2, text: "You need a key to open\nthis door." },
		/* 23 */ { course: 24, actor: "Door", icon: "Bowser Key", split: 3, text: "This key doesn't fit!\nMaybe it's for the\nbasement..." },
		/* 24 */ { course: 24, actor: "Door", icon: "Door 1 Star", split: 5, text: "You need Star power to\nopen this door. Recover a\nPower Star from an enemy\ninside one of the castle's\npaintings." },
		/* 25 */ { course: 24, actor: "Door", icon: "Door 3 Star", split: 4, text: "It takes the power of\n3 Stars to open this\ndoor. You need %d more\nStars." },
		/* 26 */ { course: 24, icon: "Star Door", split: 4, text: "It takes the power of\n8 Stars to open this\ndoor. You need %d more\nStars." },
		/* 27 */ { course: 24, icon: "Star Door", split: 4, text: "It takes the power of\n30 Stars to open this\ndoor. You need %d more\nStars." },
		/* 28 */ { course: 24, icon: "Star Door", split: 4, text: "It takes the power of\n50 Stars to open this\ndoor. You need %d more\nStars." },
		/* 29 */ { course: 24, icon: "Star Door", split: 5, text: 'To open the door that\nleads to the "endless"\nstairs, you need 70\nStars.\nBwa ha ha!' },
		/* 30 */ { course: 1, actor: "Lakitu", icon: "Camera Lakitu", split: 6, text: "Hello! The Lakitu Bros.,\ncutting in with a live\nupdate on Mario's\nprogress. He's about to\nlearn a technique for\nsneaking up on enemies.\nThe trick is this: He has\nto walk very slowly in\norder to walk quietly.\n\n\n\nAnd wrapping up filming\ntechniques reported on\nearlier, you can take a\nlook around using [C]→ and\n[C]←. Press [C]↓ to view the\naction from a distance.\nWhen you can't move the\ncamera any farther, the\nbuzzer will sound. This is\nthe Lakitu Bros.,\nsigning off." },
		/* 31 */ { course: 12, actor: "Koopa the Quick", icon: "Koopa the Quick with Flag", split: 5, text: "No way! You beat me...\nagain!! And I just spent\nmy entire savings on\nthese new Koopa\nMach 1 Sprint shoes!\nHere, I guess I have to\nhand over this Star to\nthe winner of the race.\nCongrats, Mario!" },
		/* 32 */ { course: [0, 7], icon: "Sign", split: 5, text: "If you get the Wing Cap,\nyou can fly! Put the cap\non, then do a Triple\nJump--jump three times\nin a row--to take off.\nYou can fly even higher\nif you blast out of a\ncannon wearing the\nWing Cap!\n\nUse the [C] Buttons to look\naround while flying, and\npress [Z] to land." },
		/* 33 */ { course: 25, actor: "Level Entrance", icon: "Warp Pipe", split: 6, text: "Ciao! You've reached\nPrincess Toadstool's\ncastle via a warp pipe.\nUsing the controller is a\npiece of cake. Press [A] to\njump and [B] to attack.\nPress [B] to read signs,\ntoo. Use the Control Stick\nin the center of the\ncontroller to move Mario\naround. Now, head for\nthe castle." },
		/* 34 */ { course: 25, icon: "Lakitu", split: 6, text: "Good afternoon. The\nLakitu Bros., here,\nreporting live from just\noutside the Princess's\ncastle.\n\nMario has just arrived\non the scene, and we'll\nbe filming the action live\nas he enters the castle\nand pursues the missing\nPower Stars.\nAs seasoned cameramen,\nwe'll be shooting from the\nrecommended angle, but\nyou can change the\ncamera angle by pressing\nthe [C] Buttons.\nIf we can't adjust the\nview any further, we'll\nbuzz. To take a look at\nthe surroundings, stop\nand press [C]↑.\n\nPress [A] to resume play.\nSwitch camera modes with\nthe [R] Button. Signs along\nthe way will review these\ninstructions.\n\nFor now, reporting live,\nthis has been the\nLakitu Bros." },
		/* 35 */ { course: 0, icon: "Sign", split: 5, text: "There are four camera, or\n\"[C],\" Buttons. Press [C]↑\nto look around using the\nControl Stick.\n\nYou'll usually see Mario\nthrough Lakitu's camera.\nIt is the camera\nrecommended for normal\nplay.\nYou can change angles by\npressing [C]→. If you press\n[R], the view switches to\nMario's camera, which\nis directly behind him.\nPress [R] again to return\nto Lakitu's camera. Press\n[C]↓ to see Mario from\nafar, using either\nLakitu's or Mario's view." },
		/* 36 */ { course: 1, icon: "Sign", split: 5, text: "OBSERVATION PLATFORM\nPress [C]↑ to take a look\naround. Don't miss\nanything!\n\nPress [R] to switch to\nMario's camera. It\nalways follows Mario.\nPress [R] again to switch\nto Lakitu's camera.\nPause the game and\nswitch the mode to \"fix\"\nthe camera in place while\nholding [R]. Give it a try!" },
		/* 37 */ { course: 3, icon: "Penguin", split: 2, text: "I win! You lose!\nHa ha ha ha!\nYou're no slouch, but I'm\na better sledder!\nBetter luck next time!" },
		/* 38 */ { course: 24, actor: "Door", icon: "Door 0 Star", split: 3, text: "Reacting to the Star\npower, the door slowly\nopens." },
		/* 39 */ { course: 0, icon: "Sign", split: 4, text: "No visitors allowed,\nby decree of\nthe Big Bob-omb\n\nI shall never surrender my\nStars, for they hold the\npower of the castle in\ntheir glow.\nThey were a gift from\nBowser, the Koopa King\nhimself, and they lie well\nhidden within my realm.\nNot a whisper of their\nwhereabouts shall leave\nmy lips. Oh, all right,\nperhaps one hint:\nHeed the Star names at\nthe beginning of the\ncourse.\n//--The Big Bob-omb" },
		/* 40 */ { course: 3, icon: "Sign", split: 3, text: "Warning!\nCold, Cold Crevasse\nBelow!" },
		/* 41 */ { course: 0, actor: "Koopa the Quick", icon: "Koopa the Quick with Flag", split: 3, text: "I win! You lose!\nHa ha ha!\n\nThat's what you get for\nmessin' with Koopa the\nQuick.\nBetter luck next time!" },
		/* 42 */ { course: 1, icon: "Sign", split: 4, text: "Caution! Narrow Bridge!\nCross slowly!\n\n\nYou can jump to the edge\nof the cliff and hang on,\nand you can climb off the\nedge if you move slowly.\nWhen you want to let go,\neither press [Z] or press\nthe Control Stick in the\ndirection of Mario's back.\nTo climb up, press Up on\nthe Control Stick. To\nscurry up quickly, press\nthe [A] Button." },
		/* 43 */ { course: [7, 5], icon: "Sign", split: 5, text: "If you jump and hold the\n[A] Button, you can hang on\nto some objects overhead.\nIt's the same as grabbing\na flying bird!" },
		/* 44 */ { course: 1, icon: "Hoot", split: 5, text: "Whooo's there? Whooo\nwoke me up? It's still\ndaylight--I should be\nsleeping!\n\nHey, as long as I'm\nawake, why not take a\nshort flight with me?\nPress and hold [A] to grab\non. Release [A] to let go.\nI'll take you wherever\nyou want to go, as long\nas my wings hold out.\nWatch my shadow, and\ngrab on." },
		/* 45 */ { course: 1, icon: "Hoot", split: 6, text: "Whew! I'm just about\nflapped out. You should\nlay off the pasta, Mario!\nThat's it for now. Press\n[A] to let go. Okay,\nbye byyyyyyeeee!" },
		/* 46 */ { course: 24, icon: "Bulletin Board", split: 5, text: "You have to master three\nimportant jumping\ntechniques.\nFirst try the Triple Jump.\n\nRun fast, then jump three\ntimes, one, two, three.\nIf you time the jumps\nright, you'll hop, skip,\nthen jump really high.\nNext, go for distance\nwith the Long Jump. Run,\npress [Z] to crouch then [A]\nto jump really far.\n\nTo do the Wall Kick, press\n[A] to jump at a wall, then\njump again when you hit\nthe wall.\n\nGot that? Triple Jump,\nLong Jump, Wall Kick.\nPractice, practice,\npractice. You don't stand\na chance without them." },
		/* 47 */ { icon: "Bob-omb Buddy", split: 2, text: "Hi! I'll prepare the\ncannon for you!" },
		/* 48 */ { course: 3, actor: "Level Entrance", icon: "Mario", split: 4, text: "Snow Mountain Summit\nWatch for slippery\nconditions! Please enter\nthe cottage first." },
		/* 49 */ { course: 4, icon: "Sign", split: 5, text: "Remember that tricky Wall\nKick jump? It's a\ntechnique you'll have to\nmaster in order to reach\nhigh places.\nUse it to jump from wall\nto wall. Press the\nControl Stick in the\ndirection you want to\nbounce to gain momentum.\nPractice makes perfect!" },
		/* 50 */ { course: [0, 5], icon: "Sign", split: 4, text: "Hold [Z] to crouch and\nslide down a slope.\nOr press [Z] while in the\nair to Pound the Ground!\nIf you stop, crouch, then\njump, you'll do a\nBackward Somersault!\nGot that?\nThere's more. Crouch and\nthen jump to do a\nLong Jump! Or crouch and\nwalk to...never mind." },
		/* 51 */ { course: [25, 1, 2], icon: "Sign", split: 6, text: "Climbing's easy! When you\njump at trees, poles or\npillars, you'll grab them\nautomatically. Press [A] to\njump off backward.\n\nTo rotate around the\nobject, press Right or\nLeft on the Control Stick.\nWhen you reach the top,\npress Up to do a\nhandstand!\nJump off from the\nhandstand for a high,\nstylin' dismount." },
		/* 52 */ { course: 24, icon: "Bulletin Board", split: 5, text: "Stop and press [Z] to\ncrouch, then press [A]\nto do a high, Backward\nSomersault!\n\nTo perform a Side\nSomersault, run, do a\nsharp U-turn and jump.\nYou can catch lots of\nair with both jumps." },
		/* 53 */ { course: [0, 8, 10], icon: "Sign", split: 5, text: "Sometimes, if you pass\nthrough a coin ring or\nfind a secret point in a\ncourse, a red number will\nappear.\nIf you trigger five red\nnumbers, a secret Star\nwill show up." },
		/* 54 */ { course: 3, icon: "Sign", split: 5, text: "Welcome to the snow\nslide! Hop on! To speed\nup, press forward on the\nControl Stick. To slow\ndown, pull back." },
		/* 55 */ { course: 3, icon: "Penguin", split: 4, text: "Hey-ey, Mario, buddy,\nhowzit goin'? Step right\nup. You look like a fast\nsleddin' kind of guy.\nI know speed when I see\nit, yes siree--I'm the\nworld champion sledder,\nyou know. Whaddya say?\nHow about a race?\nReady...\n\n//Go//// Don't Go" },
		/* 56 */ { course: 3, icon: "Penguin", split: 6, text: "You brrrr-oke my record!\nUnbelievable! I knew\nthat you were the coolest.\nNow you've proven\nthat you're also the\nfastest!\nI can't award you a gold\nmedal, but here, take this\nStar instead. You've\nearned it!" },
		/* 57 */ { course: 3, icon: "Penguin", split: 4, text: "Egad! My baby!! Have you\nseen my baby??? She's\nthe most precious baby in\nthe whole wide world.\n(They say she has my\nbeak...) I just can't\nremember where I left\nher.\nLet's see...I stopped\nfor herring and ice cubes,\nthen I...oohh! I just\ndon't know!" },
		/* 58 */ { course: 3, icon: "Penguin", split: 4, text: "You found my precious,\nprecious baby! Where\nhave you been? How can\nI ever thank you, Mario?\nOh, I do have this...\n...Star. Here, take it\nwith my eternal\ngratitude." },
		/* 59 */ { course: 3, icon: "Penguin", split: 4, text: "That's not my baby! She\nlooks nothing like me!\nHer parents must be\nworried sick!" },
		/* 60 */ { course: 2, icon: "Sign", split: 4, text: "ATTENTION!\nRead Before Diving In!\n\n\nIf you stay under the\nwater for too long, you'll\nrun out of oxygen.\n\nReturn to the surface for\nair or find an air bubble\nor coins to breathe while\nunderwater.\nPress [A] to swim. Hold [A]\nto swim slow and steady.\nTap [A] with smooth timing\nto gain speed.\nPress Up on the\nControl Stick and press [A]\nto dive.\n\nPress Down on the Control\nStick and press [A] to\nreturn to the surface.\n\nHold Down and press [A]\nwhile on the surface near\nthe edge of the water to\njump out." },
		/* 61 */ { course: 9, icon: "Sign", split: 4, text: "BRRR! Frostbite Danger!\nDo not swim here.\nI'm serious.\n/--The Penguin" },
		/* 62 */ { course: 5, icon: "Sign", split: 3, text: "Hidden inside the green\nblock is the amazing\nMetal Cap.\nWearing it, you won't\ncatch fire or be hurt\nby enemy attacks.\nYou don't even have to\nbreathe while wearing it.\n\nThe only problem:\nYou can't swim in it." },
		/* 63 */ { course: 4, icon: "Sign", split: 5, text: "The Vanish Cap is inside\nthe blue block. Mr. I.\nwill be surprised, since\nyou'll be invisible when\nyou wear it!\nEven the Big Boo will be\nfooled--and you can walk\nthrough secret walls, too." },
		/* 64 */ { course: 0, icon: "Sign", split: 5, text: "When you put on the Wing\nCap that comes from a\nred block, do the Triple\nJump to soar high into\nthe sky.\nUse the Control Stick to\nguide Mario. Pull back to\nto fly up, press forward\nto nose down, and press [Z]\nto land." },
		/* 65 */ { course: 2, icon: "Sign", split: 6, text: "Swimming Lessons!\nTap [A] to do the breast\nstroke. If you time the\ntaps right, you'll swim\nfast.\n\nPress and hold [A] to do a\nslow, steady flutter kick.\nPress Up on the Control\nStick to dive, and pull\nback on the stick to head\nfor the surface.\nTo jump out of the water,\nhold Down on the Control\nStick, then press [A].\nEasy as pie, right?\n\n\nBut remember:\nMario can't breathe under\nthe water! Return to the\nsurface for air when the\nPower Meter runs low.\n\nAnd one last thing: You\ncan't open doors that\nare underwater." },
		/* 66 */ { course: 15, icon: "Sign", split: 5, text: "Mario, it's Peach!\nPlease be careful! Bowser\nis so wicked! He will try\nto burn you with his\nhorrible flame breath.\nRun around behind and\ngrab him by the tail with\nthe [B] Button. Once you\ngrab hold, swing him\naround in great circles.\nRotate the Control Stick\nto go faster and faster.\nThe faster you swing him,\nthe farther he'll fly.\n\nUse the [C] Buttons to look\naround, Mario. You have\nto throw Bowser into one\nof the bombs in the four\ncorners.\nAim well, then press [B]\nagain to launch Bowser.\nGood luck, Mario! Our\nfate is in your hands." },
		/* 67 */ { course: 15, icon: "Bowser", split: 5, text: "Tough luck, Mario!\nPrincess Toadstool isn't\nhere...Gwa ha ha!! Go\nahead--just try to grab\nme by the tail!\nYou'll never be able to\nswing ME around! A wimp\nlike you won't throw me\nout of here! Never! Ha!" },
		/* 68 */ { course: 6, icon: "Sign", split: 5, text: "It's Lethal Lava Land!\nIf you catch fire or fall\ninto a pool of flames,\nyou'll be hopping mad, but\ndon't lose your cool.\nYou can still control\nMario--just try to keep\ncalm!" },
		/* 69 */ { course: 24, icon: "Bulletin Board", split: 6, text: "Sometimes you'll bump into\ninvisible walls at the\nedges of the painting\nworlds. If you hit a wall\nwhile flying, you'll bounce\nback." },
		/* 70 */ { course: 24, icon: "Bulletin Board", split: 5, text: "You can return to the\ncastle's main hall at any\ntime from the painting\nworlds where the enemies\nlive.\nJust stop, stand still,\npress Start to pause the\ngame, then select\n\"Exit Course.\"\n\nYou don't have to collect\nall Power Stars in one\ncourse before going on to\nthe next.\n\nReturn later, when you're\nmore experienced, to pick\nup difficult ones.\n\n\nWhenever you find a Star,\na hint for finding the\nnext one will appear on\nthe course's start screen.\n\nYou can, however, collect\nany of the remaining\nStars next. You don't\nhave to recover the one\ndescribed by the hint." },
		/* 71 */ { course: 5, icon: "Sign", split: 3, text: "Danger Ahead!\nBeware of the strange\ncloud! Don't inhale!\nIf you feel faint, run for\nhigher ground and fresh\nair!\nCircle: Shelter\nArrow: Entrance-Exit" },
		/* 72 */ { course: 11, icon: "Sign", split: 5, text: "High winds ahead!\nPull your Cap down tight.\nIf it blows off, you'll\nhave to find it on this\nmountain." },
		/* 73 */ { course: 2, icon: "Sign", split: 4, text: "Aarrgh! Ahoy, matey. I\nhave sunken treasure,\nhere, I do.\n\nBut to pluck the plunder,\nyou must open the\nTreasure Chests in the\nright order.\nWhat order is that,\nye say?\n\n\nI'll never tell!\n\n//--The Cap'n" },
		/* 74 */ { course: 0, icon: "Sign", split: 5, text: "You can grab on to the\nedge of a cliff or ledge\nwith your fingertips and\nhang down from it.\n\nTo drop from the edge,\neither press the Control\nStick in the direction of\nMario's back or press the\n[Z] Button.\nTo get up onto the ledge,\neither press Up on the\nControl Stick or press [A]\nas soon as you grab the\nledge to climb up quickly." },
		/* 75 */ { course: 24, icon: "Bulletin Board", split: 5, text: "Mario!! My castle is in\ngreat peril. I know that\nBowser is the cause...and\nI know that only you can\nstop him!\nThe doors in the castle\nthat have been sealed by\nBowser can be opened only\nwith Star Power.\n\nBut there are secret\npaths in the castle,\npaths that Bowser hasn't\nfound.\n\nOne of those paths is in\nthis room, and it holds\none of the castle's Secret\nStars!\n\nFind that Secret Star,\nMario! It will help you\non your quest. Please,\nMario, you have to\nhelp us!\nRetrieve all of the\nPower Stars in the castle\nand free us from this\nawful prison!\nPlease!" },
		/* 76 */ { course: 24, icon: "Toad", split: 6, text: "Thanks to the power of\nthe Stars, life is\nreturning to the castle.\nPlease, Mario, you have\nto give Bowser the boot!\n\nHere, let me tell you a\nlittle something about the\ncastle. In the room with\nthe mirrors, look carefully\nfor anything that's not\nreflected in the mirror.\nAnd when you go to the\nwater town, you can flood\nit with a high jump into\nthe painting. Oh, by the\nway, look what I found!" },
		/* 77 */ { course: 24, icon: "Bulletin Board", split: 2, text: "It is decreed that one\nshall pound the pillars." },
		/* 78 */ { course: 1, icon: "Sign", split: 5, text: "Break open the Blue Coin\nBlock by Pounding the\nGround with the [Z] Button.\nOne Blue Coin is worth\nfive Yellow Coins.\nBut you have to hurry!\nThe coins will disappear\nif you're not quick to\ncollect them! Too bad." },
		/* 79 */ { course: 11, icon: "Ukiki", split: 4, text: "Owwwuu! Let me go!\nUukee-kee! I was only\nteasing! Can't you take\na joke?\nI'll tell you what, let's\ntrade. If you let me go,\nI'll give you something\nreally good.\nSo, how about it?\n\n//Free him/ Hold on" },
		/* 80 */ { course: 11, icon: "Ukiki", split: 1, text: "Eeeh hee hee hee!" },
		/* 81 */ { course: 10, icon: "Sign", split: 4, text: "The mystery is of Wet\nor Dry.\nAnd where does the\nsolution lie?\nThe city welcomes visitors\nwith the depth they bring\nas they enter." },
		/* 82 */ { course: 24, icon: "Toad", split: 4, text: "Hold on to your hat! If\nyou lose it, you'll be\ninjured easily.\n\nIf you do lose your Cap,\nyou'll have to find it in\nthe course where you\nlost it.\nOh, boy, it's not looking\ngood for Peach. She's\nstill trapped somewhere\ninside the walls.\nPlease, Mario, you have\nto help her! Did you know\nthat there are enemy\nworlds inside the walls?\nYup. It's true. Bowser's\ntroops are there, too.\nOh, here, take this. I've\nbeen keeping it for you." },
		/* 83 */ { course: 24, icon: "Toad", split: 6, text: "There's something strange\nabout that clock. As you\njump inside, watch the\nposition of the big hand.\nOh, look what I found!\nHere, Mario, catch!" },
		/* 84 */ { course: 24, icon: "MIPS", split: 3, text: "Yeeoww! Unhand me,\nbrute! I'm late, so late,\nI must make haste!\nThis shiny thing? Mine!\nIt's mine. Finders,\nkeepers, losers...\nLate, late, late...\nOuch! Take it then! A\ngift from Bowser, it was.\nNow let me be! I have a\ndate! I cannot be late\nfor tea!" },
		/* 85 */ { course: 4, icon: "Sign", split: 5, text: "You don't stand a ghost\nof a chance in this house.\nIf you walk out of here,\nyou deserve...\n...a Ghoul Medal..." },
		/* 86 */ { course: [4, 6, 9], icon: "Sign", split: 3, text: "Running around in circles\nmakes some bad guys roll\ntheir eyes." },
		/* 87 */ { course: 3, icon: "Sign", split: 4, text: "Santa Claus isn't the only\none who can go down a\nchimney! Come on in!\n/--Cabin Proprietor" },
		/* 88 */ { course: 5, icon: "Sign", split: 5, text: "Work Elevator\nFor those who get off\nhere: Grab the pole to the\nleft and slide carefully\ndown." },
		/* 89 */ { course: 5, icon: "Sign", split: 5, text: "Both ways fraught with\ndanger! Watch your feet!\nThose who can't do the\nLong Jump, tsk, tsk. Make\nyour way to the right.\nRight: Work Elevator\n/// Cloudy Maze\nLeft: Black Hole\n///Underground Lake\n\nRed Circle: Elevator 2\n//// Underground Lake\nArrow: You are here" },
		/* 90 */ { course: 15, actor: " Bowser", icon: "Bowser Breathing", split: 6, text: "Bwa ha ha ha!\nYou've stepped right into\nmy trap, just as I knew\nyou would! I warn you,\n\"Friend,\" watch your\nstep!" },
		/* 91 */ { course: 3, icon: "Sign", split: 2, text: "Danger!\nStrong Gusts!\nBut the wind makes a\ncomfy ride." },
		/* 92 */ { course: 16, actor: "Bowser", icon: "Bowser Breathing", split: 5, text: "Pestering me again, are\nyou, Mario? Can't you see\nthat I'm having a merry\nlittle time, making\nmischief with my minions?\nNow, return those Stars!\nMy troops in the walls\nneed them! Bwa ha ha!" },
		/* 93 */ { course: 17, actor: "Bowser", icon: "Bowser Breathing", split: 5, text: "Mario! You again! Well\nthat's just fine--I've\nbeen looking for something\nto fry with my fire\nbreath!\nYour Star Power is\nuseless against me!\nYour friends are all\ntrapped within the\nwalls...\nAnd you'll never see the\nPrincess again!\nBwa ha ha ha!" },
		/* 94 */ { course: [3, 11], icon: "Sign", split: 4, text: "Get a good run up the\nslope! Do you remember\nthe Long Jump? Run, press\n[Z], then jump!" },
		/* 95 */ { course: 0, icon: "Sign", split: 4, text: "To read a sign, stand in\nfront of it and press [B],\nlike you did just now.\n\nWhen you want to talk to\na Koopa Troopa or other\nanimal, stand right in\nfront of it.\nPlease recover the Stars\nthat were stolen by\nBowser in this course." },
		/* 96 */ { course: 1, icon: "Sign", split: 4, text: "The path is narrow here.\nEasy does it! No one is\nallowed on top of the\nmountain!\nAnd if you know what's\ngood for you, you won't\nwake anyone who's\nsleeping!\nMove slowly,\ntread lightly." },
		/* 97 */ { course: 6, actor: "Level Entrance", icon: "LLL Rotating Hexagonal Platform", split: 5, text: "Don't be a pushover!\nIf anyone tries to shove\nyou around, push back!\nIt's one-on-one, with a\nfiery finish for the loser!" },
		/* 98 */ { course: 4, actor: "Level Entrance", icon: "Big Boo", split: 2, text: "Come on in here...\n...heh, heh, heh..." },
		/* 99 */ { split: 5, text: "Eh he he...\nYou're mine, now, hee hee!\nI'll pass right through\nthis wall. Can you do\nthat? Heh, heh, heh!" },
		/* 100 */ { course: 11, icon: "Ukiki", split: 3, text: "Ukkiki...\u200bWakkiki...\u200bkee kee!\nHa! I snagged it!\nIt's mine! Heeheeheeee!" },
		/* 101 */ { course: 11, icon: "Ukiki", split: 3, text: "Ackk! Let...\u200bgo...\nYou're...\u200bchoking...\u200bme...\nCough...\u200bI've been framed!\nThis Cap? Oh, all right,\ntake it. It's a cool Cap,\nbut I'll give it back.\nI think it looks better on\nme than it does on you,\nthough! Eeeee! Kee keee!" },
		/* 102 */ { course: 25, icon: "Sign", split: 5, text: "Pssst! The Boos are super\nshy. If you look them\nin the eyes, they fade\naway, but if you turn\nyour back, they reappear.\nIt's no use trying to hit\nthem when they're fading\naway. Instead, sneak up\nbehind them and punch." },
		/* 103 */ { course: 7, icon: "Sign", split: 4, text: "Upon four towers\none must alight...\nThen at the peak\nshall shine the light..." },
		/* 104 */ { course: [0, 1], icon: "Sign", split: 5, text: 'The shadowy star in front\nof you is a "Star\nMarker." When you collect\nall 8 Red Coins, the Star\nwill appear here.' },
		/* 105 */ { icon: "Bob-omb Buddy", split: 3, text: "Ready for blastoff! Come\non, hop into the cannon!\n\nYou can reach the Star on\nthe floating island by\nusing the four cannons.\nUse the Control Stick to\naim, then press [A] to fire.\n\nIf you're handy, you can\ngrab on to trees or poles\nto land." },
		/* 106 */ { icon: "Bob-omb Buddy", split: 2, text: "Ready for blastoff! Come\non, hop into the cannon!" },
		/* 107 */ { course: 4, icon: "Boo", split: 3, text: "Ghosts...\n...don't...\n...DIE!\nHeh, heh, heh!\nCan you get out of here...\n...alive?" },
		/* 108 */ { course: 4, icon: "Big Boo", split: 2, text: "Boooooo-m! Here comes\nthe master of mischief,\nthe tower of terror,\nthe Big Boo!\nKa ha ha ha..." },
		/* 109 */ { course: 3, icon: "Snowman's Head", split: 4, text: "Ooooo Nooooo!\nTalk about out-of-body\nexperiences--my body\nhas melted away!\nHave you run in to any\nheadhunters lately??\nI could sure use a new\nbody!\nBrrr! My face might\nfreeze like this!" },
		/* 110 */ { course: 3, icon: "Snowman's Body", split: 5, text: "I need a good head on my\nshoulders. Do you know of\nanybody in need of a good\nbody? Please! I'll follow\nyou if you do!" },
		/* 111 */ { course: 3, icon: "Snowman", split: 4, text: "Perfect! What a great\nnew body! Here--this is a\npresent for you. It's sure\nto warm you up." },
		/* 112 */ { course: 0, icon: "Sign", split: 4, text: "Collect as many coins as\npossible! They'll refill\nyour Power Meter.\n\nYou can check to see how\nmany coins you've\ncollected in each of the\n15 enemy worlds.\nYou can also recover\npower by touching the\nSpinning Heart.\n\nThe faster you run\nthrough the heart, the\nmore power you'll recover." },
		/* 113 */ { course: [0, 1, 2], icon: "Sign", split: 6, text: "There are special Caps in\nthe red, green and blue\nblocks. Step on the\nswitches in the hidden\ncourses to activate the\nCap Blocks." },
		/* 114 */ { course: 1, icon: "King Whomp", split: 5, text: "It makes me so mad! We\nbuild your houses, your\ncastles. We pave your\nroads, and still you\nwalk all over us.\nDo you ever say thank\nyou? No! Well, you're not\ngoing to wipe your feet\non me! I think I'll crush\nyou just for fun!\nDo you have a problem\nwith that? Just try to\npound me, wimp! Ha!" },
		/* 115 */ { course: 1, icon: "King Whomp", split: 5, text: "No! Crushed again!\nI'm just a stepping stone,\nafter all. I won't gravel,\ner, grovel. Here, you win.\nTake this with you!" },
		/* 116 */ { course: 0, icon: "King Bob-omb", split: 5, text: "Whaaa....\u200bWhaaat?\nCan it be that a\npipsqueak like you has\ndefused the Bob-omb\nking????\nYou might be fast enough\nto ground me, but you'll\nhave to pick up the pace\nif you want to take King\nBowser by the tail.\nMethinks my troops could\nlearn a lesson from you!\nHere is your Star, as I\npromised, Mario.\n\nIf you want to see me\nagain, select this Star\nfrom the menu. For now,\nfarewell." },
		/* 117 */ { course: 7, actor: "Eyerok", icon: "Eyerok Left Hand", split: 1, text: "Who...\u200bwalk...\u200bhere?\nWho...\u200bbreak...\u200bseal?\nWake..\u200bancient..\u200bones?\nWe no like light...\nRrrrummbbble...\nWe no like...\u200bintruders!\nNow battle...\n...\u200bhand...\n...\u200bto...\n...hand!" },
		/* 118 */ { course: 7, actor: "Eyerok", icon: "Eyerok Right Hand", split: 6, text: "Grrrrumbbble!\nWhat...\u200bhappen?\nWe...\u200bcrushed like pebble.\nYou so strong!\nYou rule ancient pyramid!\nFor today...\nNow, take Star of Power.\nWe...\u200bsleep...\u200bdarkness." },
		/* 119 */ { course: 15, actor: "Bowser", icon: "Bowser Breathing", split: 6, text: "Grrr! I was a bit\ncareless. This is not as I\nhad planned...but I still\nhold the power of the\nStars, and I still have\nPeach.\nBwa ha ha! You'll get no\nmore Stars from me! I'm\nnot finished with you yet,\nbut I'll let you go for\nnow. You'll pay for this...\nlater!" },
		/* 120 */ { course: 16, actor: "Bowser", icon: "Bowser Breathing", split: 4, text: "Ooowaah! Can it be that\nI've lost??? The power of\nthe Stars has failed me...\nthis time.\nConsider this a draw.\nNext time, I'll be in\nperfect condition.\n\nNow, if you want to see\nyour precious Princess,\ncome to the top of the\ntower.\nI'll be waiting!\nGwa ha ha ha!" },
		/* 121 */ { course: 17, actor: "Bowser", icon: "Bowser Breathing", split: 5, text: "Nooo! It can't be!\nYou've really beaten me,\nMario?!! I gave those\ntroops power, but now\nit's fading away!\nArrgghh! I can see peace\nreturning to the world! I\ncan't stand it! Hmmm...\nIt's not over yet...\n\nC'mon troops! Let's watch\nthe ending together!\nBwa ha ha!" },
		/* 122 */ { course: 5, icon: "Sign", split: 4, text: "The Black Hole\nRight: Work Elevator\n/// Cloudy Maze\nLeft: Underground Lake" },
		/* 123 */ { course: 19, icon: "Sign", split: 4, text: "Metal Cavern\nRight: To Waterfall\nLeft: Metal Cap Switch" },
		/* 124 */ { course: 5, icon: "Sign", split: 4, text: "Work Elevator\nDanger!!\nRead instructions\nthoroughly!\nElevator continues in the\ndirection of the arrow\nactivated." },
		/* 125 */ { course: 5, icon: "Sign", split: 3, text: "Hazy Maze-Exit\nDanger! Closed.\nTurn back now." },
		/* 126 */ { course: 5, icon: "Sign", split: 4, text: "Up: Black Hole\nRight: Work Elevator\n/// Hazy Maze" },
		/* 127 */ { course: 5, icon: "Sign", split: 4, text: "Underground Lake\nRight: Metal Cave\nLeft: Abandoned Mine\n///(Closed)\nA gentle sea dragon lives\nhere. Pound on his back to\nmake him lower his head.\nDon't become his lunch." },
		/* 128 */ { course: 0, icon: "King Bob-omb", split: 4, text: "You must fight with\nhonor! It is against the\nroyal rules to throw the\nking out of the ring!" },
		/* 129 */ { course: 21, actor: "Level Entrance", icon: "Mario", split: 5, text: "Welcome to the Vanish\nCap Switch Course! All of\nthe blue blocks you find\nwill become solid once you\nstep on the Cap Switch.\nYou'll disappear when you\nput on the Vanish Cap, so\nyou'll be able to elude\nenemies and walk through\nmany things. Try it out!" },
		/* 130 */ { course: 19, actor: "Level Entrance", icon: "Mario", split: 5, text: "Welcome to the Metal Cap\nSwitch Course! Once you\nstep on the Cap Switch,\nthe green blocks will\nbecome solid.\nWhen you turn your body\ninto metal with the Metal\nCap, you can walk\nunderwater! Try it!" },
		/* 131 */ { course: 20, actor: "Level Entrance", icon: "Mario", split: 5, text: "Welcome to the Wing Cap\nCourse! Step on the red\nswitch at the top of the\ntower, in the center of\nthe rainbow ring.\nWhen you trigger the\nswitch, all of the red\nblocks you find will\nbecome solid.\n\nTry out the Wing Cap! Do\nthe Triple Jump to take\noff and press [Z] to land.\n\n\nPull back on the Control\nStick to go up and push\nforward to nose down,\njust as you would when\nflying an airplane." },
		/* 132 */ { course: 3, icon: "Penguin", split: 4, text: "Whoa, Mario, pal, you\naren't trying to cheat,\nare you? Shortcuts aren't\nallowed.\nNow, I know that you\nknow better. You're\ndisqualified! Next time,\nplay fair!" },
		/* 133 */ { course: 24, icon: "Toad", split: 6, text: "Am I glad to see you! The\nPrincess...and I...and,\nwell, everybody...we're all\ntrapped inside the castle\nwalls.\n\nBowser has stolen the\ncastle's Stars, and he's\nusing their power to\ncreate his own world in\nthe paintings and walls.\n\nPlease recover the Power\nStars! As you find them,\nyou can use their power\nto open the doors that\nBowser has sealed.\n\nThere are four rooms on\nthe first floor. Start in\nthe one with the painting\nof Bob-omb inside. It's\nthe only room that Bowser\nhasn't sealed.\nWhen you collect eight\nPower Stars, you'll be\nable to open the door\nwith the big star. The\nPrincess must be inside!" },
		/* 134 */ { course: 24, icon: "Toad", split: 5, text: "The names of the Stars\nare also hints for\nfinding them. They are\ndisplayed at the beginning\nof each course.\nYou can collect the Stars\nin any order. You won't\nfind some Stars, enemies\nor items unless you select\na specific Star.\nAfter you collect some\nStars, you can try\nanother course.\nWe're all waiting for\nyour help!" },
		/* 135 */ { course: 24, icon: "Toad", split: 5, text: "It was Bowser who stole\nthe Stars. I saw him with\nmy own eyes!\n\n\nHe's hidden six Stars in\neach course, but you\nwon't find all of them in\nsome courses until you\npress the Cap Switches.\nThe Stars you've found\nwill show on each course's\nstarting screen.\n\n\nIf you want to see some\nof the enemies you've\nalready defeated, select\nthe Stars you recovered\nfrom them." },
		/* 136 */ { course: 24, icon: "Toad", split: 6, text: "Wow! You've already\nrecovered that many\nStars? Way to go, Mario!\nI'll bet you'll have us out\nof here in no time!\n\nBe careful, though.\nBowser and his band\nwrote the book on \"bad.\"\nTake my advice: When you\nneed to recover from\ninjuries, collect coins.\nYellow Coins refill one\npiece of the Power Meter,\nRed Coins refill two\npieces, and Blue Coins\nrefill five.\n\nTo make Blue Coins\nappear, pound on Blue\nCoin Blocks.\n\n\n\nAlso, if you fall from\nhigh places, you'll\nminimize damage if you\nPound the Ground as you\nland." },
		/* 137 */ { course: 24, icon: "Toad", split: 6, text: "Thanks, Mario! The castle\nis recovering its energy\nas you retrieve Power\nStars, and you've chased\nBowser right out of here,\non to some area ahead.\nOh, by the by, are you\ncollecting coins? Special\nStars appear when you\ncollect 100 coins in each\nof the 15 courses!" },
		/* 138 */ { course: 5, icon: "Sign", split: 3, text: "Down: Underground Lake\nLeft: Black Hole\nRight: Hazy Maze (Closed)" },
		/* 139 */ { course: 5, icon: "Sign", split: 6, text: "Above: Automatic Elevator\nElevator begins\nautomatically and follows\npre-set course.\nIt disappears\nautomatically, too." },
		/* 140 */ { course: 5, icon: "Sign", split: 6, text: "Elevator Area\nRight: Hazy Maze\n/// Entrance\nLeft: Black Hole\n///Elevator 1\nArrow: You are here" },
		/* 141 */ { course: 24, actor: "Level Exit", icon: "Power Star Yellow", split: 5, text: "You've recovered one of\nthe stolen Power Stars!\nNow you can open some of\nthe sealed doors in the\ncastle.\nTry the Princess's room\non the second floor and\nthe room with the\npainting of Whomp's\nFortress on Floor 1.\nBowser's troops are still\ngaining power, so you\ncan't give up. Save us,\nMario! Keep searching for\nStars!" },
		/* 142 */ { course: 24, actor: "Level Exit", icon: "Power Star Yellow", split: 5, text: "You've recovered three\nPower Stars! Now you can\nopen any door with a 3\non its star.\n\nYou can come and go from\nthe open courses as you\nplease. The enemies ahead\nare even meaner, so be\ncareful!" },
		/* 143 */ { course: 24, actor: "Level Exit", icon: "Power Star Yellow", split: 6, text: "You've recovered eight of\nthe Power Stars! Now you\ncan open the door with\nthe big Star! But Bowser\nis just ahead...can you\nhear the Princess calling?" },
		/* 144 */ { course: 24, actor: "Level Exit", icon: "Power Star Yellow", split: 6, text: "You've recovered 30\nPower Stars! Now you can\nopen the door with the\nbig Star! But before you\nmove on, how's it going\notherwise?\nDid you pound the two\ncolumns down? You didn't\nlose your hat, did you?\nIf you did, you'll have to\nstomp on the condor to\nget it back!\nThey say that Bowser has\nsneaked out of the sea\nand into the underground.\nHave you finally\ncornered him?" },
		/* 145 */ { course: 24, actor: "Level Exit", icon: "Power Star Yellow", split: 6, text: "You've recovered 50\nPower Stars! Now you can\nopen the Star Door on the\nthird floor. Bowser's\nthere, you know.\n\nOh! You've found all of\nthe Cap Switches, haven't\nyou? Red, green and blue?\nThe Caps you get from the\ncolored blocks are really\nhelpful.\nHurry along, now. The\nthird floor is just ahead." },
		/* 146 */ { course: 24, actor: "Level Exit", icon: "Power Star Yellow", split: 6, text: "You've found 70 Power\nStars! The mystery of the\nendless stairs is solved,\nthanks to you--and is\nBowser ever upset! Now,\non to the final bout!" },
		/* 147 */ { course: 24, icon: "Bulletin Board", split: 5, text: "Are you using the Cap\nBlocks? You really should,\nyou know.\n\n\nTo make them solid so you\ncan break them, you have\nto press the colored Cap\nSwitches in the castle's\nhidden courses.\nYou'll find the hidden\ncourses only after\nregaining some of the\nPower Stars.\n\nThe Cap Blocks are a big\nhelp! Red for the Wing\nCap, green for the Metal\nCap, blue for the Vanish\nCap." },
		/* 148 */ { course: 9, icon: "Sign", split: 6, text: "Snowman Mountain ahead.\nKeep out! And don't try\nthe Triple Jump over the\nice block shooter.\n\n\nIf you fall into the\nfreezing pond, your power\ndecreases quickly, and\nyou won't recover\nautomatically.\n//--The Snowman" },
		/* 149 */ { course: 18, icon: "Sign", split: 3, text: "Welcome to\nPrincess Toadstool's\nsecret slide!\nThere's a Star hidden\nhere that Bowser couldn't\nfind.\nWhen you slide, press\nforward to speed up,\npull back to slow down.\nIf you slide really\nfast, you'll win the Star!" },
		/* 150 */ { course: 12, icon: "Wiggler", split: 5, text: "Waaaa! You've flooded my\nhouse! Wh-why?? Look at\nthis mess! What am I\ngoing to do now?\n\nThe ceiling's ruined, the\nfloor is soaked...what to\ndo, what to do? Huff...\nhuff...it makes me so...\nMAD!!!\nEverything's been going\nwrong ever since I got\nthis Star...It's so shiny,\nbut it makes me feel...\nstrange..." },
		/* 151 */ { course: 12, icon: "Wiggler", split: 4, text: "I can't take this\nanymore! First you get\nme all wet, then you\nstomp on me!\nNow I'm really, really,\nREALLY mad!\nWaaaaaaaaaaaaaaaaa!!!" },
		/* 152 */ { course: 12, icon: "Wiggler", split: 3, text: "Owwch! Uncle! Uncle!\nOkay, I give. Take this\nStar!\nWhew! I feel better now.\nI don't really need it\nanymore, anyway--\nI can see the stars\nthrough my ceiling at\nnight.\nThey make me feel...\n...peaceful. Please, come\nback and visit anytime." },
		/* 153 */ { course: 9, icon: "Snowman", split: 4, text: "Hey! Who's there?\nWhat's climbing on me?\nIs it an ice ant?\nA snow flea?\nWhatever it is, it's\nbugging me! I think I'll\nblow it away!" },
		/* 154 */ { course: 24, icon: "Toad", split: 5, text: "Hold on to your hat! If\nyou lose it, you'll be\neasily injured. If you\nlose it, look for it in the\ncourse where you lost it.\nSpeaking of lost, the\nPrincess is still stuck in\nthe walls somewhere.\nPlease help, Mario!\n\nOh, you know that there\nare secret worlds in the\nwalls as well as in the\npaintings, right?" },
		/* 155 */ { course: 24, icon: "Toad", split: 6, text: "Thanks to the power of\nthe Stars, life is\nreturning to the castle.\nPlease, Mario, you have\nto give Bowser the boot!\n\nHere, let me tell you a\nlittle something about the\ncastle. In the room with\nthe mirrors, look carefully\nfor anything that's not\nreflected in the mirror.\nAnd when you go to the\nwater town, you can flood\nit with a high jump into\nthe painting." },
		/* 156 */ { course: 24, icon: "Toad", split: 5, text: "The world inside the\nclock is so strange!\nWhen you jump inside,\nwatch the position of\nthe big hand!" },
		/* 157 */ { course: 7, icon: "Sign", split: 5, text: "Watch out! Don't let\nyourself be swallowed by\nquicksand.\n\n\nIf you sink into the sand,\nyou won't be able to\njump, and if your head\ngoes under, you'll be\nsmothered.\nThe dark areas are\nbottomless pits." },
		/* 158 */ { course: 25, icon: "Sign", split: 6, text: "1. If you jump repeatedly\nand time it right, you'll\njump higher and higher.\nIf you run really fast and\ntime three jumps right,\nyou can do a Triple Jump.\n2. Jump into a solid wall,\nthen jump again when you\nhit the wall. You can\nbounce to a higher level\nusing this Wall Kick." },
		/* 159 */ { course: 25, icon: "Sign", split: 6, text: "3. If you stop, press [Z]\nto crouch, then jump, you\ncan perform a Backward\nSomersault. To do a Long\nJump, run fast, press [Z],\nthen jump." },
		/* 160 */ { course: [25, 4], icon: "Sign", split: 4, text: "Press [B] while running\nfast to do a Body Slide\nattack. To stand while\nsliding, press [A] or [B]." },
		/* 161 */ { course: 25, icon: "Yoshi", split: 4, text: "Mario!!!\nIt that really you???\nIt has been so long since\nour last adventure!\nThey told me that I might\nsee you if I waited here,\nbut I'd just about given\nup hope!\nIs it true? Have you\nreally beaten Bowser? And\nrestored the Stars to the\ncastle?\nAnd saved the Princess?\nI knew you could do it!\nNow I have a very special\nmessage for you.\n\"Thanks for playing Super\nMario 64! This is the\nend of the game, but not\nthe end of the fun.\nWe want you to keep on\nplaying, so we have a\nlittle something for you.\nWe hope that you like it!\nEnjoy!!!\"\n\nThe Super Mario 64 Team" },
		/* 162 */ { course: 24, icon: "MIPS", split: 4, text: "No, no, no! Not you\nagain! I'm in a great\nhurry, can't you see?\n\nI've no time to squabble\nover Stars. Here, have it.\nI never meant to hide it\nfrom you...\nIt's just that I'm in such\na rush. That's it, that's\nall. Now, I must be off.\nOwww! Let me go!" },
		/* 163 */ { course: 17, actor: "Bowser", icon: "Bowser Breathing", split: 5, text: "Noooo! You've really\nbeaten me this time,\nMario! I can't stand\nlosing to you!\n\nMy troops...worthless!\nThey've turned over all\nthe Power Stars! What?!\nThere are 120 in all???\n\nAmazing! There were some\nin the castle that I\nmissed??!!\n\n\nNow I see peace\nreturning to the world...\nOooo! I really hate that!\nI can't watch--\nI'm outta here!\nJust you wait until next\ntime. Until then, keep\nthat Control Stick\nsmokin'!\nBuwaa ha ha!" },
		/* 164 */ { course: 3, icon: "Penguin", split: 4, text: "Mario! What's up, pal?\nI haven't been on the\nslide lately, so I'm out\nof shape.\nStill, I'm always up for a\ngood race, especially\nagainst an old sleddin'\nbuddy.\nWhaddya say?\nReady...\u200bset...\n\n//Go//// Don't Go" },
		/* 165 */ { course: 12, icon: "Sign", split: 5, text: "I take no responsibility\nwhatsoever for those who\nget dizzy and pass out\nfrom running around\nthis post." },
		/* 166 */ { course: 12, icon: "Sign", split: 4, text: "I'll be back soon.\nI'm out training now,\nso come back later.\n//--Koopa the Quick" },
		/* 167 */ { course: 25, icon: "Sign", split: 4, text: "Princess Toadstool's\ncastle is just ahead.\n\n\nPress [A] to jump, [Z] to\ncrouch, and [B] to punch,\nread a sign, or grab\nsomething.\nPress [B] again to throw\nsomething you're holding." },
		/* 168 */ { course: 12, icon: "Wiggler", split: 5, text: "Hey! Knock it off! That's\nthe second time you've\nnailed me. Now you're\nasking for it, linguine\nbreath!" },
		/* 169 */ { course: 2, icon: "Sign", split: 4, text: "Keep out!\nThat means you!\nArrgghh!\n\nAnyone entering this cave\nwithout permission will\nmeet certain disaster." }
	], dialogListLinks: {
		source: "https://github.com/Matojeje/mato-bot/blob/master/resources/sm64.js#L151",
		descriptions: "https://gitlab.com/Pilzinsel64/sm64-rom-manager/blob/master/SM64%20ROM%20Manager/bin/Debug/Data/Text%20Manager/dialogs.txt"
	}
}