module.exports = {
	imgUrl: "https://rawcdn.githack.com/SM64-TAS-ABC/STROOP/c260e427ad9e4533b4eb00845059478cd7307b57/STROOP/Resources/Object Images/",
	courses: [
		"Bob-omb Battlefield",
		"Whomp's Fortress",
		"Jolly Roger Bay",
		"Cool, Cool Mountain",
		"Big Boo's Haunt",
		"Hazy Maze Cave",
		"Lethal Lava Land",
		"Shifting Sand Land",
		"Dire, Dire Docks",
		"Snowman's Land",
		"Wet-Dry World",
		"Tall, Tall Mountain",
		"Tiny-Huge Island",
		"Tick-Tock Clock",
		"Rainbow Ride",
		"Bowser in the Dark World",
		"Bowser in the Fire Sea",
		"Bowser in the Sky",
		"The Princess's Secret Slide",
		"Cavern of the Metal Cap",
		"Tower of the Wing Cap",
		"Vanish Cap under the Moat",
		"Wing Mario Over the Rainbow",
		"The Secret Aquarium",
		"Inside Castle",
		"Castle Grounds"
	], stars: [
		{ course: 0, id: 1, name: "Big Bob-omb on the Summit" },
		{ course: 0, id: 2, name: "Footrace with Koopa the Quick" },
		{ course: 0, id: 3, name: "Shoot to the Island in the Sky" },
		{ course: 0, id: 4, name: "Find the 8 Red Coins" },
		{ course: 0, id: 5, name: "Mario Wings to the Sky" },
		{ course: 0, id: 6, name: "Behind Chain Chomp's Gate" },

		{ course: 1, id: 1, name: "Chip Off Whomp's Block" },
		{ course: 1, id: 2, name: "To the Top of the Fortress" },
		{ course: 1, id: 3, name: "Shoot into the Wild Blue" },
		{ course: 1, id: 4, name: "Red Coins on the Floating Isle" },
		{ course: 1, id: 5, name: "Fall onto the Caged Island" },
		{ course: 1, id: 6, name: "Blast Away the Wall" },

		{ course: 2, id: 1, name: "Plunder in the Sunken Ship" },
		{ course: 2, id: 2, name: "Can the Eel Come Out to Play?" },
		{ course: 2, id: 3, name: "Treasure of the Ocean Cave" },
		{ course: 2, id: 4, name: "Red Coins on the Ship Afloat" },
		{ course: 2, id: 5, name: "Blast to the Stone Pillar" },
		{ course: 2, id: 6, name: "Through the Jet Stream" },

		{ course: 3, id: 1, name: "Slip Slidin' Away" },
		{ course: 3, id: 2, name: "Li'l Penguin Lost" },
		{ course: 3, id: 3, name: "Big Penguin Race" },
		{ course: 3, id: 4, name: "Frosty Slide for 8 Red Coins" },
		{ course: 3, id: 5, name: "Snowman's Lost His Head" },
		{ course: 3, id: 6, name: "Wall Kicks Will Work" },

		{ course: 4, id: 1, name: "Go on a Ghost Hunt" },
		{ course: 4, id: 2, name: "Ride Big Boo's Merry-Go-Round" },
		{ course: 4, id: 3, name: "Secret of the Haunted Books" },
		{ course: 4, id: 4, name: "Seek the 8 Red Coins" },
		{ course: 4, id: 5, name: "Big Boo's Balcony" },
		{ course: 4, id: 6, name: "Eye to Eye in the Secret" },

		{ course: 5, id: 1, name: "Swimming Beast in the Cavern" },
		{ course: 5, id: 2, name: "Elevate for 8 Red Coins" },
		{ course: 5, id: 3, name: "Metal-Head Mario Can Move!" },
		{ course: 5, id: 4, name: "Navigating the Toxic Maze" },
		{ course: 5, id: 5, name: "A-Maze-Ing Emergency Exit" },
		{ course: 5, id: 6, name: "Watch for Rolling Rocks" },

		{ course: 6, id: 1, name: "Boil the Big Bully" },
		{ course: 6, id: 2, name: "Bully the Bullies" },
		{ course: 6, id: 3, name: "8-Coin Puzzle with 15 Pieces" },
		{ course: 6, id: 4, name: "Red-Hot Log Rolling" },
		{ course: 6, id: 5, name: "Hot-Foot-It into the Volcano" },
		{ course: 6, id: 6, name: "Elevator Tour in the Volcano" },

		{ course: 7, id: 1, name: "In the Talons of the Big Bird" },
		{ course: 7, id: 2, name: "Shining Atop the Pyramid" },
		{ course: 7, id: 3, name: "Inside the Ancient Pyramid" },
		{ course: 7, id: 4, name: "Stand Tall on the Four Pillars" },
		{ course: 7, id: 5, name: "Free Flying for 8 Red Coins" },
		{ course: 7, id: 6, name: "Pyramid Puzzle" },

		{ course: 8, id: 1, name: "Board Bowser's Sub" },
		{ course: 8, id: 2, name: "Chests in the Current" },
		{ course: 8, id: 3, name: "Pole-Jumping for Red Coins" },
		{ course: 8, id: 4, name: "Through the Jet Stream" },
		{ course: 8, id: 5, name: "The Manta Ray's Reward" },
		{ course: 8, id: 6, name: "Collect the Caps..." },

		{ course: 9, id: 1, name: "Snowman's Big Head" },
		{ course: 9, id: 2, name: "Chill with the Bully" },
		{ course: 9, id: 3, name: "In the Deep Freeze" },
		{ course: 9, id: 4, name: "Whirl from the Freezing Pond" },
		{ course: 9, id: 5, name: "Shell Shreddin' for Red Coins" },
		{ course: 9, id: 6, name: "Into the Igloo" },

		{ course: 10, id: 1, name: "Shocking Arrow Lifts!" },
		{ course: 10, id: 2, name: "Top o' the Town" },
		{ course: 10, id: 3, name: "Secrets in the Shallows & Sky" },
		{ course: 10, id: 4, name: "Express Elevator--Hurry Up!" },
		{ course: 10, id: 5, name: "Go to Town for Red Coins" },
		{ course: 10, id: 6, name: "Quick Race Through Downtown!" },

		{ course: 11, id: 1, name: "Scale the Mountain" },
		{ course: 11, id: 2, name: "Mystery of the Monkey Cage" },
		{ course: 11, id: 3, name: "Scary 'Shrooms, Red Coins" },
		{ course: 11, id: 4, name: "Mysterious Mountainside" },
		{ course: 11, id: 5, name: "Breathtaking View from Bridge" },
		{ course: 11, id: 6, name: "Blast to the Lonely Mushroom" },

		{ course: 12, id: 1, name: "Pluck the Piranha Flower" },
		{ course: 12, id: 2, name: "The Tip Top of the Huge Island" },
		{ course: 12, id: 3, name: "Rematch with Koopa the Quick" },
		{ course: 12, id: 4, name: "Five Itty Bitty Secrets" },
		{ course: 12, id: 5, name: "Wiggler's Red Coins" },
		{ course: 12, id: 6, name: "Make Wiggler Squirm" },

		{ course: 13, id: 1, name: "Roll into the Cage" },
		{ course: 13, id: 2, name: "The Pit and the Pendulums" },
		{ course: 13, id: 3, name: "Get a Hand" },
		{ course: 13, id: 4, name: "Stomp on the Thwomp" },
		{ course: 13, id: 5, name: "Timed Jumps on Moving Bars" },
		{ course: 13, id: 6, name: "Stop Time for Red Coins" },

		{ course: 14, id: 1, name: "Cruiser Crossing the Rainbow" },
		{ course: 14, id: 2, name: "The Big House in the Sky" },
		{ course: 14, id: 3, name: "Coins Amassed in a Maze" },
		{ course: 14, id: 4, name: "Swingin' in the Breeze" },
		{ course: 14, id: 5, name: "Tricky Triangles!" },
		{ course: 14, id: 6, name: "Somewhere Over the Rainbow" },

		{ course: 18, id: 1, name: "One of the Castle's Secret Stars!" },
		{ course: 18, id: 2, name: "One of the Castle's Secret Stars!" },
		{ course: 23, id: 1, name: "One of the Castle's Secret Stars!" },
		{ course: 15, id: 1, name: "One of the Castle's Secret Stars!" },
		{ course: 24, id: 1, name: "One of the Castle's Secret Stars!" },
		{ course: 24, id: 2, name: "One of the Castle's Secret Stars!" },
		{ course: 24, id: 3, name: "One of the Castle's Secret Stars!" },
		{ course: 20, id: 1, name: "One of the Castle's Secret Stars!" },
		{ course: 19, id: 1, name: "One of the Castle's Secret Stars!" },
		{ course: 21, id: 1, name: "One of the Castle's Secret Stars!" },
		{ course: 24, id: 4, name: "One of the Castle's Secret Stars!" },
		{ course: 24, id: 5, name: "One of the Castle's Secret Stars!" },
		{ course: 16, id: 1, name: "One of the Castle's Secret Stars!" },
		{ course: 22, id: 1, name: "One of the Castle's Secret Stars!" },
		{ course: 17, id: 1, name: "One of the Castle's Secret Stars!" }
	], dialogs: [
		{ course: 0, actor: "Level Entrance", icon: "Mario", split: 4, text: "Wow! You're smack in the\nmiddle of the battlefield.\nYou'll find the Power\nStars that Bowser stole\ninside the painting\nworlds.\nFirst, talk to the\nBob-omb Buddy. (Press [B]\nto talk.) He'll certainly\nhelp you out, and so will\nhis comrades in other\nareas.\nTo read signs, stop, face\nthem and press [B]. Press [A]\nor [B] to scroll ahead. You\ncan talk to some other\ncharacters by facing them\nand pressing [B]." },
		{ course: 0, icon: "Bob-omb Buddy", split: 4, text: "Watch out! If you wander\naround here, you're liable\nto be plastered by a\nwater bomb!\nThose enemy Bob-ombs love\nto fight, and they're\nalways finding ways to\nattack.\nThis meadow has become\na battlefield ever since\nthe Big Bob-omb got his\npaws on the Power Star.\nCan you recover the Star\nfor us? Cross the bridge\nand go left up the path\nto find the Big Bob-omb.\nPlease come back to see\nme after you've retrieved\nthe Power Star!" },
		{ course: 0, icon: "Bob-omb Buddy", split: 4, text: "Hey, you! It's dangerous\nahead, so listen up! Take\nmy advice.\n\nCross the two\nbridges ahead, then\nwatch for falling\nwater bombs.\nThe Big Bob-omb at the\ntop of the mountain is\nvery powerful--don't let\nhim grab you!\nWe're Bob-omb Buddies,\nand we're on your side.\nYou can talk to us\nwhenever you'd like to!" },
		{ course: 0, icon: "Bob-omb Buddy", split: 5, text: "Thank you, Mario! The Big\nBob-omb is nothing but a\nbig dud now! But the\nbattle for the castle has\njust begun.\nOther enemies are holding\nthe other Power Stars. If\nyou recover more Stars,\nyou can open new doors\nthat lead to new worlds!\nMy Bob-omb Buddies are\nwaiting for you. Be sure\nto talk to them--they'll\nset up cannons for you." },
		{ course: 0, icon: "Bob-omb Buddy", split: 3, text: "We're peace-loving\nBob-ombs, so we don't use\ncannons.\nBut if you'd like\nto blast off, we don't\nmind. Help yourself.\nWe'll prepare all of the\ncannons in this course for\nyou to use. Bon Voyage!" },
		{ course: 0, icon: "Koopa the Quick", split: 3, text: "Hey, Mario! Is it true\nthat you beat the Big\nBob-omb? Cool!\nYou must be strong. And\npretty fast. So, how fast\nare you, anyway?\nFast enough to beat me...\nKoopa the Quick? I don't\nthink so. Just try me.\nHow about a race to the\nmountaintop, where the\nBig Bob-omb was?\nWhaddya say? When I say\n\"Go,\" let the race begin!\n\nReady....\n\n//Go!////Don't Go" },
		{ course: 0, actor: "Koopa the Quick", icon: "Koopa the Quick with Flag", split: 3, text: "Hey!!! Don't try to scam\nME. You've gotta run\nthe whole course.\nLater. Look me up when\nyou want to race for\nreal." },
		{ course: 0, actor: "Koopa the Quick", icon: "Koopa the Quick with Flag", split: 5, text: "Hufff...\u200bfff...\u200bpufff...\nWhoa! You...\u200breally...\u200bare...\nfast! A human blur!\nHere you go--\u200byou've won\nit, fair and square!" },
		{ course: 0, icon: "Sign", split: 4, text: "BEWARE OF CHAIN CHOMP\nExtreme Danger!\nGet close and press [C]↑\nfor a better look.\nScary, huh?\nSee the Red Coin on top\nof the stake?\n\nWhen you collect eight of\nthem, a Power Star will\nappear in the meadow\nacross the bridge." },
		{ course: 12, icon: "Koopa the Quick", split: 4, text: "Long time, no see! Wow,\nhave you gotten fast!\nHave you been training\non the sly, or is it the\npower of the Stars?\nI've been feeling down\nabout losing the last\nrace. This is my home\ncourse--how about a\nrematch?\nThe goal is in\nWindswept Valley.\nReady?\n\n//Go//// Don't Go" },
		{ course: 20, icon: "Wing Cap Switch Button", split: 4, text: "You've stepped on the\nWing Cap Switch. Wearing\nthe Wing Cap, you can\nsoar through the sky.\nNow Wing Caps will pop\nout of all the red blocks\nyou find.\n\nWould you like to Save?\n\n//Yes////No" },
		{ course: 19, icon: "Metal Cap Switch Button", split: 4, text: "You've just stepped on\nthe Metal Cap Switch!\nThe Metal Cap makes\nMario invincible.\nNow Metal Caps will\npop out of all of the\ngreen blocks you find.\n\nWould you like to Save?\n\n//Yes////No" },
		{ course: 21, icon: "Vanish Cap Switch Button", split: 4, text: "You've just stepped on\nthe Vanish Cap Switch.\nThe Vanish Cap makes\nMario disappear.\nNow Vanish Caps will pop\nfrom all of the blue\nblocks you find.\n\nWould you like to Save?\n\n//Yes////No" },
		{ actor: "Level Exit", icon: "Power Star Yellow", split: 5, text: "You've collected 100\ncoins! Mario gains more\npower from the castle.\nDo you want to Save?\n//Yes////No" },
		{ actor: "Level Exit", icon: "Power Star Yellow", split: 4, text: "Wow! Another Power Star!\nMario gains more courage\nfrom the power of the\ncastle.\nDo you want to Save?\n\n//You Bet//Not Now" },
		{ course: 0, icon: "Sign", split: 4, text: "You can punch enemies to\nknock them down. Press [A]\nto jump, [B] to punch.\nPress [A] then [B] to Kick.\nTo pick something up,\npress [B], too. To throw\nsomething you're holding,\npress [B] again." },
		{ course: [7, 6, 9], icon: "Sign", split: 3, text: "Hop on the shiny shell and\nride wherever you want to\ngo! Shred those enemies!" },
		{ course: 0, icon: "King Bob-omb", split: 4, text: "I'm the Big Bob-omb, lord\nof all blasting matter,\nking of ka-booms the\nworld over!\nHow dare you scale my\nmountain? By what right\ndo you set foot on my\nimperial mountaintop?\nYou may have eluded my\nguards, but you'll never\nescape my grasp...\n\n...and you'll never take\naway my Power Star. I\nhereby challenge you,\nMario!\nIf you want the Star I\nhold, you must prove\nyourself in battle.\n\nCan you pick me up from\nthe back and hurl me to\nthis royal turf? I think\nthat you cannot!" },
		{ course: 1, icon: "Sign", split: 4, text: "I'm sleeping because...\n...I'm sleepy. I don't\nlike being disturbed.\nPlease walk quietly." },
		{ course: 24, icon: "Bulletin Board", split: 2, text: "Shhh! Please walk\nquietly in the hallway!" },
		{ course: 25, icon: "Peach", split: 6, text: "Dear Mario:\nPlease come to the\ncastle. I've baked\na cake for you.\nYours truly--\nPrincess Toadstool" },
		{ course: 24, actor: "Bowser", icon: "Bowser Breathing", split: 5, text: "Welcome.\nNo one's home!\nNow scram--\nand don't come back!\nGwa ha ha!" },
		{ course: 24, actor: "Door", icon: "Door Key", split: 2, text: "You need a key to open\nthis door." },
		{ course: 24, actor: "Door", icon: "Bowser Key", split: 3, text: "This key doesn't fit!\nMaybe it's for the\nbasement..." },
		{ course: 24, actor: "Door", icon: "Door 1 Star", split: 5, text: "You need Star power to\nopen this door. Recover a\nPower Star from an enemy\ninside one of the castle's\npaintings." },
		{ course: 24, actor: "Door", icon: "Door 3 Star", split: 4, text: "It takes the power of\n3 Stars to open this\ndoor. You need %d more\nStars." },
		{ course: 24, icon: "Star Door", split: 4, text: "It takes the power of\n8 Stars to open this\ndoor. You need %d more\nStars." },
		{ course: 24, icon: "Star Door", split: 4, text: "It takes the power of\n30 Stars to open this\ndoor. You need %d more\nStars." },
		{ course: 24, icon: "Star Door", split: 4, text: "It takes the power of\n50 Stars to open this\ndoor. You need %d more\nStars." },
		{ course: 24, icon: "Star Door", split: 5, text: 'To open the door that\nleads to the "endless"\nstairs, you need 70\nStars.\nBwa ha ha!' },
		{ course: 1, actor: "Lakitu", icon: "Camera Lakitu", split: 6, text: "Hello! The Lakitu Bros.,\ncutting in with a live\nupdate on Mario's\nprogress. He's about to\nlearn a technique for\nsneaking up on enemies.\nThe trick is this: He has\nto walk very slowly in\norder to walk quietly.\n\n\n\nAnd wrapping up filming\ntechniques reported on\nearlier, you can take a\nlook around using [C]→ and\n[C]←. Press [C]↓ to view the\naction from a distance.\nWhen you can't move the\ncamera any farther, the\nbuzzer will sound. This is\nthe Lakitu Bros.,\nsigning off." },
		{ course: 12, actor: "Koopa the Quick", icon: "Koopa the Quick with Flag", split: 5, text: "No way! You beat me...\nagain!! And I just spent\nmy entire savings on\nthese new Koopa\nMach 1 Sprint shoes!\nHere, I guess I have to\nhand over this Star to\nthe winner of the race.\nCongrats, Mario!" },
		{ course: [0, 7], icon: "Sign", split: 5, text: "If you get the Wing Cap,\nyou can fly! Put the cap\non, then do a Triple\nJump--jump three times\nin a row--to take off.\nYou can fly even higher\nif you blast out of a\ncannon wearing the\nWing Cap!\n\nUse the [C] Buttons to look\naround while flying, and\npress [Z] to land." },
		{ course: 25, actor: "Level Entrance", icon: "Warp Pipe", split: 6, text: "Ciao! You've reached\nPrincess Toadstool's\ncastle via a warp pipe.\nUsing the controller is a\npiece of cake. Press [A] to\njump and [B] to attack.\nPress [B] to read signs,\ntoo. Use the Control Stick\nin the center of the\ncontroller to move Mario\naround. Now, head for\nthe castle." },
		{ course: 25, icon: "Lakitu", split: 6, text: "Good afternoon. The\nLakitu Bros., here,\nreporting live from just\noutside the Princess's\ncastle.\n\nMario has just arrived\non the scene, and we'll\nbe filming the action live\nas he enters the castle\nand pursues the missing\nPower Stars.\nAs seasoned cameramen,\nwe'll be shooting from the\nrecommended angle, but\nyou can change the\ncamera angle by pressing\nthe [C] Buttons.\nIf we can't adjust the\nview any further, we'll\nbuzz. To take a look at\nthe surroundings, stop\nand press [C]↑.\n\nPress [A] to resume play.\nSwitch camera modes with\nthe [R] Button. Signs along\nthe way will review these\ninstructions.\n\nFor now, reporting live,\nthis has been the\nLakitu Bros." },
		{ course: 0, icon: "Sign", split: 5, text: "There are four camera, or\n\"[C],\" Buttons. Press [C]↑\nto look around using the\nControl Stick.\n\nYou'll usually see Mario\nthrough Lakitu's camera.\nIt is the camera\nrecommended for normal\nplay.\nYou can change angles by\npressing [C]→. If you press\n[R], the view switches to\nMario's camera, which\nis directly behind him.\nPress [R] again to return\nto Lakitu's camera. Press\n[C]↓ to see Mario from\nafar, using either\nLakitu's or Mario's view." },
		{ course: 1, icon: "Sign", split: 5, text: "OBSERVATION PLATFORM\nPress [C]↑ to take a look\naround. Don't miss\nanything!\n\nPress [R] to switch to\nMario's camera. It\nalways follows Mario.\nPress [R] again to switch\nto Lakitu's camera.\nPause the game and\nswitch the mode to \"fix\"\nthe camera in place while\nholding [R]. Give it a try!" },
		{ course: 3, icon: "Penguin", split: 2, text: "I win! You lose!\nHa ha ha ha!\nYou're no slouch, but I'm\na better sledder!\nBetter luck next time!" },
		{ course: 24, actor: "Door", icon: "Door 0 Star", split: 3, text: "Reacting to the Star\npower, the door slowly\nopens." },
		{ course: 0, icon: "Sign", split: 4, text: "No visitors allowed,\nby decree of\nthe Big Bob-omb\n\nI shall never surrender my\nStars, for they hold the\npower of the castle in\ntheir glow.\nThey were a gift from\nBowser, the Koopa King\nhimself, and they lie well\nhidden within my realm.\nNot a whisper of their\nwhereabouts shall leave\nmy lips. Oh, all right,\nperhaps one hint:\nHeed the Star names at\nthe beginning of the\ncourse.\n//--The Big Bob-omb" },
		{ course: 3, icon: "Sign", split: 3, text: "Warning!\nCold, Cold Crevasse\nBelow!" },
		{ course: 0, actor: "Koopa the Quick", icon: "Koopa the Quick with Flag", split: 3, text: "I win! You lose!\nHa ha ha!\n\nThat's what you get for\nmessin' with Koopa the\nQuick.\nBetter luck next time!" },
		{ course: 1, icon: "Sign", split: 4, text: "Caution! Narrow Bridge!\nCross slowly!\n\n\nYou can jump to the edge\nof the cliff and hang on,\nand you can climb off the\nedge if you move slowly.\nWhen you want to let go,\neither press [Z] or press\nthe Control Stick in the\ndirection of Mario's back.\nTo climb up, press Up on\nthe Control Stick. To\nscurry up quickly, press\nthe [A] Button." },
		{ course: [7, 5], icon: "Sign", split: 5, text: "If you jump and hold the\n[A] Button, you can hang on\nto some objects overhead.\nIt's the same as grabbing\na flying bird!" },
		{ course: 1, icon: "Hoot", split: 5, text: "Whooo's there? Whooo\nwoke me up? It's still\ndaylight--I should be\nsleeping!\n\nHey, as long as I'm\nawake, why not take a\nshort flight with me?\nPress and hold [A] to grab\non. Release [A] to let go.\nI'll take you wherever\nyou want to go, as long\nas my wings hold out.\nWatch my shadow, and\ngrab on." },
		{ course: 1, icon: "Hoot", split: 6, text: "Whew! I'm just about\nflapped out. You should\nlay off the pasta, Mario!\nThat's it for now. Press\n[A] to let go. Okay,\nbye byyyyyyeeee!" },
		{ course: 24, icon: "Bulletin Board", split: 5, text: "You have to master three\nimportant jumping\ntechniques.\nFirst try the Triple Jump.\n\nRun fast, then jump three\ntimes, one, two, three.\nIf you time the jumps\nright, you'll hop, skip,\nthen jump really high.\nNext, go for distance\nwith the Long Jump. Run,\npress [Z] to crouch then [A]\nto jump really far.\n\nTo do the Wall Kick, press\n[A] to jump at a wall, then\njump again when you hit\nthe wall.\n\nGot that? Triple Jump,\nLong Jump, Wall Kick.\nPractice, practice,\npractice. You don't stand\na chance without them." },
		{ icon: "Bob-omb Buddy", split: 2, text: "Hi! I'll prepare the\ncannon for you!" },
		{ course: 3, actor: "Level Entrance", icon: "Mario", split: 4, text: "Snow Mountain Summit\nWatch for slippery\nconditions! Please enter\nthe cottage first." },
		{ course: 4, icon: "Sign", split: 5, text: "Remember that tricky Wall\nKick jump? It's a\ntechnique you'll have to\nmaster in order to reach\nhigh places.\nUse it to jump from wall\nto wall. Press the\nControl Stick in the\ndirection you want to\nbounce to gain momentum.\nPractice makes perfect!" },
		{ course: [0, 5], icon: "Sign", split: 4, text: "Hold [Z] to crouch and\nslide down a slope.\nOr press [Z] while in the\nair to Pound the Ground!\nIf you stop, crouch, then\njump, you'll do a\nBackward Somersault!\nGot that?\nThere's more. Crouch and\nthen jump to do a\nLong Jump! Or crouch and\nwalk to...never mind." },
		{ course: [25, 1, 2], icon: "Sign", split: 6, text: "Climbing's easy! When you\njump at trees, poles or\npillars, you'll grab them\nautomatically. Press [A] to\njump off backward.\n\nTo rotate around the\nobject, press Right or\nLeft on the Control Stick.\nWhen you reach the top,\npress Up to do a\nhandstand!\nJump off from the\nhandstand for a high,\nstylin' dismount." },
		{ course: 24, icon: "Bulletin Board", split: 5, text: "Stop and press [Z] to\ncrouch, then press [A]\nto do a high, Backward\nSomersault!\n\nTo perform a Side\nSomersault, run, do a\nsharp U-turn and jump.\nYou can catch lots of\nair with both jumps." },
		{ course: [0, 8, 10], icon: "Sign", split: 5, text: "Sometimes, if you pass\nthrough a coin ring or\nfind a secret point in a\ncourse, a red number will\nappear.\nIf you trigger five red\nnumbers, a secret Star\nwill show up." },
		{ course: 3, icon: "Sign", split: 5, text: "Welcome to the snow\nslide! Hop on! To speed\nup, press forward on the\nControl Stick. To slow\ndown, pull back." },
		{ course: 3, icon: "Penguin", split: 4, text: "Hey-ey, Mario, buddy,\nhowzit goin'? Step right\nup. You look like a fast\nsleddin' kind of guy.\nI know speed when I see\nit, yes siree--I'm the\nworld champion sledder,\nyou know. Whaddya say?\nHow about a race?\nReady...\n\n//Go//// Don't Go" },
		{ course: 3, icon: "Penguin", split: 6, text: "You brrrr-oke my record!\nUnbelievable! I knew\nthat you were the coolest.\nNow you've proven\nthat you're also the\nfastest!\nI can't award you a gold\nmedal, but here, take this\nStar instead. You've\nearned it!" },
		{ course: 3, icon: "Penguin", split: 4, text: "Egad! My baby!! Have you\nseen my baby??? She's\nthe most precious baby in\nthe whole wide world.\n(They say she has my\nbeak...) I just can't\nremember where I left\nher.\nLet's see...I stopped\nfor herring and ice cubes,\nthen I...oohh! I just\ndon't know!" },
		{ course: 3, icon: "Penguin", split: 4, text: "You found my precious,\nprecious baby! Where\nhave you been? How can\nI ever thank you, Mario?\nOh, I do have this...\n...Star. Here, take it\nwith my eternal\ngratitude." },
		{ course: 3, icon: "Penguin", split: 4, text: "That's not my baby! She\nlooks nothing like me!\nHer parents must be\nworried sick!" },
		{ course: 2, icon: "Sign", split: 4, text: "ATTENTION!\nRead Before Diving In!\n\n\nIf you stay under the\nwater for too long, you'll\nrun out of oxygen.\n\nReturn to the surface for\nair or find an air bubble\nor coins to breathe while\nunderwater.\nPress [A] to swim. Hold [A]\nto swim slow and steady.\nTap [A] with smooth timing\nto gain speed.\nPress Up on the\nControl Stick and press [A]\nto dive.\n\nPress Down on the Control\nStick and press [A] to\nreturn to the surface.\n\nHold Down and press [A]\nwhile on the surface near\nthe edge of the water to\njump out." },
		{ course: 9, icon: "Sign", split: 4, text: "BRRR! Frostbite Danger!\nDo not swim here.\nI'm serious.\n/--The Penguin" },
		{ course: 5, icon: "Sign", split: 3, text: "Hidden inside the green\nblock is the amazing\nMetal Cap.\nWearing it, you won't\ncatch fire or be hurt\nby enemy attacks.\nYou don't even have to\nbreathe while wearing it.\n\nThe only problem:\nYou can't swim in it." },
		{ course: 4, icon: "Sign", split: 5, text: "The Vanish Cap is inside\nthe blue block. Mr. I.\nwill be surprised, since\nyou'll be invisible when\nyou wear it!\nEven the Big Boo will be\nfooled--and you can walk\nthrough secret walls, too." },
		{ course: 0, icon: "Sign", split: 5, text: "When you put on the Wing\nCap that comes from a\nred block, do the Triple\nJump to soar high into\nthe sky.\nUse the Control Stick to\nguide Mario. Pull back to\nto fly up, press forward\nto nose down, and press [Z]\nto land." },
		{ course: 2, icon: "Sign", split: 6, text: "Swimming Lessons!\nTap [A] to do the breast\nstroke. If you time the\ntaps right, you'll swim\nfast.\n\nPress and hold [A] to do a\nslow, steady flutter kick.\nPress Up on the Control\nStick to dive, and pull\nback on the stick to head\nfor the surface.\nTo jump out of the water,\nhold Down on the Control\nStick, then press [A].\nEasy as pie, right?\n\n\nBut remember:\nMario can't breathe under\nthe water! Return to the\nsurface for air when the\nPower Meter runs low.\n\nAnd one last thing: You\ncan't open doors that\nare underwater." },
		{ course: 15, icon: "Sign", split: 5, text: "Mario, it's Peach!\nPlease be careful! Bowser\nis so wicked! He will try\nto burn you with his\nhorrible flame breath.\nRun around behind and\ngrab him by the tail with\nthe [B] Button. Once you\ngrab hold, swing him\naround in great circles.\nRotate the Control Stick\nto go faster and faster.\nThe faster you swing him,\nthe farther he'll fly.\n\nUse the [C] Buttons to look\naround, Mario. You have\nto throw Bowser into one\nof the bombs in the four\ncorners.\nAim well, then press [B]\nagain to launch Bowser.\nGood luck, Mario! Our\nfate is in your hands." },
		{ course: 15, icon: "Bowser", split: 5, text: "Tough luck, Mario!\nPrincess Toadstool isn't\nhere...Gwa ha ha!! Go\nahead--just try to grab\nme by the tail!\nYou'll never be able to\nswing ME around! A wimp\nlike you won't throw me\nout of here! Never! Ha!" },
		{ course: 6, icon: "Sign", split: 5, text: "It's Lethal Lava Land!\nIf you catch fire or fall\ninto a pool of flames,\nyou'll be hopping mad, but\ndon't lose your cool.\nYou can still control\nMario--just try to keep\ncalm!" },
		{ course: 24, icon: "Bulletin Board", split: 6, text: "Sometimes you'll bump into\ninvisible walls at the\nedges of the painting\nworlds. If you hit a wall\nwhile flying, you'll bounce\nback." },
		{ course: 24, icon: "Bulletin Board", split: 5, text: "You can return to the\ncastle's main hall at any\ntime from the painting\nworlds where the enemies\nlive.\nJust stop, stand still,\npress Start to pause the\ngame, then select\n\"Exit Course.\"\n\nYou don't have to collect\nall Power Stars in one\ncourse before going on to\nthe next.\n\nReturn later, when you're\nmore experienced, to pick\nup difficult ones.\n\n\nWhenever you find a Star,\na hint for finding the\nnext one will appear on\nthe course's start screen.\n\nYou can, however, collect\nany of the remaining\nStars next. You don't\nhave to recover the one\ndescribed by the hint." },
		{ course: 5, icon: "Sign", split: 3, text: "Danger Ahead!\nBeware of the strange\ncloud! Don't inhale!\nIf you feel faint, run for\nhigher ground and fresh\nair!\nCircle: Shelter\nArrow: Entrance-Exit" },
		{ course: 11, icon: "Sign", split: 5, text: "High winds ahead!\nPull your Cap down tight.\nIf it blows off, you'll\nhave to find it on this\nmountain." },
		{ course: 2, icon: "Sign", split: 4, text: "Aarrgh! Ahoy, matey. I\nhave sunken treasure,\nhere, I do.\n\nBut to pluck the plunder,\nyou must open the\nTreasure Chests in the\nright order.\nWhat order is that,\nye say?\n\n\nI'll never tell!\n\n//--The Cap'n" },
		{ course: 0, icon: "Sign", split: 5, text: "You can grab on to the\nedge of a cliff or ledge\nwith your fingertips and\nhang down from it.\n\nTo drop from the edge,\neither press the Control\nStick in the direction of\nMario's back or press the\n[Z] Button.\nTo get up onto the ledge,\neither press Up on the\nControl Stick or press [A]\nas soon as you grab the\nledge to climb up quickly." },
		{ course: 24, icon: "Bulletin Board", split: 5, text: "Mario!! My castle is in\ngreat peril. I know that\nBowser is the cause...and\nI know that only you can\nstop him!\nThe doors in the castle\nthat have been sealed by\nBowser can be opened only\nwith Star Power.\n\nBut there are secret\npaths in the castle,\npaths that Bowser hasn't\nfound.\n\nOne of those paths is in\nthis room, and it holds\none of the castle's Secret\nStars!\n\nFind that Secret Star,\nMario! It will help you\non your quest. Please,\nMario, you have to\nhelp us!\nRetrieve all of the\nPower Stars in the castle\nand free us from this\nawful prison!\nPlease!" },
		{ course: 24, icon: "Toad", split: 6, text: "Thanks to the power of\nthe Stars, life is\nreturning to the castle.\nPlease, Mario, you have\nto give Bowser the boot!\n\nHere, let me tell you a\nlittle something about the\ncastle. In the room with\nthe mirrors, look carefully\nfor anything that's not\nreflected in the mirror.\nAnd when you go to the\nwater town, you can flood\nit with a high jump into\nthe painting. Oh, by the\nway, look what I found!" },
		{ course: 24, icon: "Bulletin Board", split: 2, text: "It is decreed that one\nshall pound the pillars." },
		{ course: 1, icon: "Sign", split: 5, text: "Break open the Blue Coin\nBlock by Pounding the\nGround with the [Z] Button.\nOne Blue Coin is worth\nfive Yellow Coins.\nBut you have to hurry!\nThe coins will disappear\nif you're not quick to\ncollect them! Too bad." },
		{ course: 11, icon: "Ukiki", split: 4, text: "Owwwuu! Let me go!\nUukee-kee! I was only\nteasing! Can't you take\na joke?\nI'll tell you what, let's\ntrade. If you let me go,\nI'll give you something\nreally good.\nSo, how about it?\n\n//Free him/ Hold on" },
		{ course: 11, icon: "Ukiki", split: 1, text: "Eeeh hee hee hee!" },
		{ course: 10, icon: "Sign", split: 4, text: "The mystery is of Wet\nor Dry.\nAnd where does the\nsolution lie?\nThe city welcomes visitors\nwith the depth they bring\nas they enter." },
		{ course: 24, icon: "Toad", split: 4, text: "Hold on to your hat! If\nyou lose it, you'll be\ninjured easily.\n\nIf you do lose your Cap,\nyou'll have to find it in\nthe course where you\nlost it.\nOh, boy, it's not looking\ngood for Peach. She's\nstill trapped somewhere\ninside the walls.\nPlease, Mario, you have\nto help her! Did you know\nthat there are enemy\nworlds inside the walls?\nYup. It's true. Bowser's\ntroops are there, too.\nOh, here, take this. I've\nbeen keeping it for you." },
		{ course: 24, icon: "Toad", split: 6, text: "There's something strange\nabout that clock. As you\njump inside, watch the\nposition of the big hand.\nOh, look what I found!\nHere, Mario, catch!" },
		{ course: 24, icon: "MIPS", split: 3, text: "Yeeoww! Unhand me,\nbrute! I'm late, so late,\nI must make haste!\nThis shiny thing? Mine!\nIt's mine. Finders,\nkeepers, losers...\nLate, late, late...\nOuch! Take it then! A\ngift from Bowser, it was.\nNow let me be! I have a\ndate! I cannot be late\nfor tea!" },
		{ course: 4, icon: "Sign", split: 5, text: "You don't stand a ghost\nof a chance in this house.\nIf you walk out of here,\nyou deserve...\n...a Ghoul Medal..." },
		{ course: [4, 6, 9], icon: "Sign", split: 3, text: "Running around in circles\nmakes some bad guys roll\ntheir eyes." },
		{ course: 3, icon: "Sign", split: 4, text: "Santa Claus isn't the only\none who can go down a\nchimney! Come on in!\n/--Cabin Proprietor" },
		{ course: 5, icon: "Sign", split: 5, text: "Work Elevator\nFor those who get off\nhere: Grab the pole to the\nleft and slide carefully\ndown." },
		{ course: 5, icon: "Sign", split: 5, text: "Both ways fraught with\ndanger! Watch your feet!\nThose who can't do the\nLong Jump, tsk, tsk. Make\nyour way to the right.\nRight: Work Elevator\n/// Cloudy Maze\nLeft: Black Hole\n///Underground Lake\n\nRed Circle: Elevator 2\n//// Underground Lake\nArrow: You are here" },
		{ course: 15, actor: " Bowser", icon: "Bowser Breathing", split: 6, text: "Bwa ha ha ha!\nYou've stepped right into\nmy trap, just as I knew\nyou would! I warn you,\n\"Friend,\" watch your\nstep!" },
		{ course: 3, icon: "Sign", split: 2, text: "Danger!\nStrong Gusts!\nBut the wind makes a\ncomfy ride." } /* ,
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" },
		{ course: 0, icon: "", split: 4, text: "" } */
	]
}